-- Reference data for a fresh Ops instance. Generated by the pg_dump in
-- docs/provisioning.md, then trimmed for portability (pg_dump was 18, the
-- servers run 16):
--   - dropped the global_settings rows (legacy Access table the Node app
--     ignores; held HITT folder paths)
--   - dropped the \restrict / \unrestrict psql meta-commands
--   - dropped the session SET header (SET transaction_timeout etc. are
--     pg17+ and error on 16 under ON_ERROR_STOP)
-- The pg_catalog.setval() lines at the end are kept — standard, all versions.
-- Regenerating? apply the same three trims.

--
-- PostgreSQL database dump
--


-- Dumped from database version 16.15 (Ubuntu 16.15-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 18.4

-- Started on 2026-09-02 12:05:09


--
-- TOC entry 4356 (class 0 OID 25019)
-- Dependencies: 238
-- Data for Name: biotechspectrums; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.biotechspectrums (id, spectrumdesc) VALUES (1, 'Big pharma');
INSERT INTO public.biotechspectrums (id, spectrumdesc) VALUES (2, 'Biotechs');
INSERT INTO public.biotechspectrums (id, spectrumdesc) VALUES (3, 'Academic institutions');
INSERT INTO public.biotechspectrums (id, spectrumdesc) VALUES (4, 'Public institutions');
INSERT INTO public.biotechspectrums (id, spectrumdesc) VALUES (5, 'Start-ups/Spin off');
INSERT INTO public.biotechspectrums (id, spectrumdesc) VALUES (6, 'Other');

--
-- TOC entry 4358 (class 0 OID 25059)
-- Dependencies: 244
-- Data for Name: companytypes; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.companytypes (id, companytypedesc) VALUES (1, 'Start Up');
INSERT INTO public.companytypes (id, companytypedesc) VALUES (2, 'Spin off');
INSERT INTO public.companytypes (id, companytypedesc) VALUES (3, 'Pharmaceutical');
INSERT INTO public.companytypes (id, companytypedesc) VALUES (4, 'Consultancy');
INSERT INTO public.companytypes (id, companytypedesc) VALUES (5, 'NGO');
INSERT INTO public.companytypes (id, companytypedesc) VALUES (6, 'GOV not research');
INSERT INTO public.companytypes (id, companytypedesc) VALUES (7, 'Research entity');
INSERT INTO public.companytypes (id, companytypedesc) VALUES (8, 'Other');
INSERT INTO public.companytypes (id, companytypedesc) VALUES (9, 'Hospital');
INSERT INTO public.companytypes (id, companytypedesc) VALUES (10, 'University');
INSERT INTO public.companytypes (id, companytypedesc) VALUES (11, 'Industrial Technology Devices');

--
-- TOC entry 4360 (class 0 OID 25079)
-- Dependencies: 250
-- Data for Name: countries; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (1, 'Afghanistan', false, 93);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (2, 'Albania', false, 355);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (3, 'Algeria', false, 213);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (4, 'American Samoa', false, 1684);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (5, 'Andorra', false, 376);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (6, 'Angola', false, 244);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (7, 'Anguilla', false, 1264);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (8, 'Antarctica', false, 672);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (9, 'Antigua and Barbuda', false, 1268);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (10, 'Argentina', false, 54);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (11, 'Armenia', false, 374);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (12, 'Aruba', false, 297);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (13, 'Australia', false, 61);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (14, 'Austria', false, 43);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (15, 'Azerbaijan', false, 994);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (16, 'Bahamas', false, 1242);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (17, 'Bahrain', false, 973);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (18, 'Bangladesh', false, 880);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (19, 'Barbados', false, 1246);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (20, 'Belarus', false, 375);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (21, 'Belgium', true, 32);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (22, 'Belize', false, 501);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (23, 'Benin', false, 229);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (24, 'Bermuda', false, 1441);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (25, 'Bhutan', false, 975);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (26, 'Bolivia', false, 591);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (27, 'Bosnia and Herzegovina', false, 387);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (28, 'Botswana', false, 267);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (29, 'Brazil', false, 55);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (30, 'British Indian Ocean Territory', false, 246);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (31, 'British Virgin Islands', false, 1284);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (32, 'Brunei', false, 673);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (33, 'Bulgaria', false, 359);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (34, 'Burkina Faso', false, 226);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (35, 'Burundi', false, 257);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (36, 'Cambodia', false, 855);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (37, 'Cameroon', false, 237);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (38, 'Canada', false, 1);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (39, 'Cape Verde', false, 238);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (40, 'Cayman Islands', false, 1345);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (41, 'Central African Republic', false, 236);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (42, 'Chad', false, 235);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (43, 'Chile', false, 56);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (44, 'China', false, 86);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (45, 'Christmas Island', false, 61);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (46, 'Cocos Islands', false, 61);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (47, 'Colombia', false, 57);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (48, 'Comoros', false, 269);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (49, 'Cook Islands', false, 682);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (50, 'Costa Rica', false, 506);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (51, 'Croatia', false, 385);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (52, 'Cuba', false, 53);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (53, 'Curacao', false, 599);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (54, 'Cyprus', false, 357);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (55, 'Czech Republic', false, 420);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (56, 'Democratic Republic of the Congo', false, 243);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (57, 'Denmark', false, 45);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (58, 'Djibouti', false, 253);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (59, 'Dominica', false, 1767);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (60, 'Dominican Republic', false, 1809);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (61, 'East Timor', false, 670);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (62, 'Ecuador', false, 593);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (63, 'Egypt', false, 20);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (64, 'El Salvador', false, 503);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (65, 'Equatorial Guinea', false, 240);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (66, 'Eritrea', false, 291);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (67, 'Estonia', false, 372);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (68, 'Ethiopia', false, 251);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (69, 'Falkland Islands', false, 500);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (70, 'Faroe Islands', false, 298);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (71, 'Fiji', false, 679);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (72, 'Finland', false, 358);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (73, 'France', true, 33);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (74, 'French Polynesia', false, 689);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (75, 'Gabon', false, 241);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (76, 'Gambia', false, 220);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (77, 'Georgia', false, 995);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (78, 'Germany', true, 49);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (79, 'Ghana', false, 233);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (80, 'Gibraltar', false, 350);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (81, 'Greece', false, 30);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (82, 'Greenland', false, 299);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (83, 'Grenada', false, 1473);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (84, 'Guam', false, 1671);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (85, 'Guatemala', false, 502);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (86, 'Guernsey', false, 441481);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (87, 'Guinea', false, 224);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (88, 'Guinea-Bissau', false, 245);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (89, 'Guyana', false, 592);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (90, 'Haiti', false, 509);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (91, 'Honduras', false, 504);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (92, 'Hong Kong', false, 852);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (93, 'Hungary', false, 36);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (94, 'Iceland', false, 354);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (95, 'India', false, 91);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (96, 'Indonesia', false, 62);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (97, 'Iran', false, 98);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (98, 'Iraq', false, 964);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (99, 'Ireland', true, 353);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (100, 'Isle of Man', false, 441624);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (101, 'Israel', false, 972);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (102, 'Italy', true, 39);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (103, 'Ivory Coast', false, 225);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (104, 'Jamaica', false, 1876);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (105, 'Japan', false, 81);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (106, 'Jersey', false, 441534);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (107, 'Jordan', false, 962);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (108, 'Kazakhstan', false, 7);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (109, 'Kenya', false, 254);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (110, 'Kiribati', false, 686);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (111, 'Kosovo', false, 383);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (112, 'Kuwait', false, 965);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (113, 'Kyrgyzstan', false, 996);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (114, 'Laos', false, 856);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (115, 'Latvia', false, 371);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (116, 'Lebanon', false, 961);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (117, 'Lesotho', false, 266);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (118, 'Liberia', false, 231);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (119, 'Libya', false, 218);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (120, 'Liechtenstein', false, 423);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (121, 'Lithuania', false, 370);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (122, 'Luxembourg', true, 352);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (123, 'Macau', false, 853);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (124, 'Macedonia', false, 389);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (125, 'Madagascar', false, 261);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (126, 'Malawi', false, 265);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (127, 'Malaysia', false, 60);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (128, 'Maldives', false, 960);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (129, 'Mali', false, 223);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (130, 'Malta', false, 356);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (131, 'Marshall Islands', false, 692);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (132, 'Mauritania', false, 222);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (133, 'Mauritius', false, 230);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (134, 'Mayotte', false, 262);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (135, 'Mexico', true, 52);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (136, 'Micronesia', false, 691);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (137, 'Moldova', false, 373);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (138, 'Monaco', false, 377);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (139, 'Mongolia', false, 976);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (140, 'Montenegro', false, 382);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (141, 'Montserrat', false, 1664);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (142, 'Morocco', false, 212);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (143, 'Mozambique', false, 258);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (144, 'Myanmar', false, 95);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (145, 'Namibia', false, 264);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (146, 'Nauru', false, 674);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (147, 'Nepal', false, 977);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (148, 'Netherlands', true, 31);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (149, 'Netherlands Antilles', false, 599);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (150, 'New Caledonia', false, 687);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (151, 'New Zealand', false, 64);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (152, 'Nicaragua', false, 505);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (153, 'Niger', false, 227);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (154, 'Nigeria', false, 234);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (155, 'Niue', false, 683);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (156, 'North Korea', false, 850);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (157, 'Northern Mariana Islands', false, 1670);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (158, 'Norway', false, 47);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (159, 'Oman', false, 968);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (160, 'Pakistan', false, 92);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (161, 'Palau', false, 680);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (162, 'Palestine', false, 970);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (163, 'Panama', false, 507);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (164, 'Papua New Guinea', false, 675);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (165, 'Paraguay', false, 595);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (166, 'Peru', false, 51);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (167, 'Philippines', false, 63);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (168, 'Pitcairn', false, 64);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (169, 'Poland', false, 48);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (170, 'Portugal', true, 351);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (171, 'Puerto Rico', false, 1787);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (172, 'Qatar', false, 974);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (173, 'Republic of the Congo', false, 242);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (174, 'Reunion', false, 262);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (175, 'Romania', false, 40);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (176, 'Russia', false, 7);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (177, 'Rwanda', false, 250);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (178, 'Saint Barthelemy', false, 590);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (179, 'Saint Helena', false, 290);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (180, 'Saint Kitts and Nevis', false, 1869);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (181, 'Saint Lucia', false, 1758);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (182, 'Saint Martin', false, 590);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (183, 'Saint Pierre and Miquelon', false, 508);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (184, 'Saint Vincent and the Grenadines', false, 1784);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (185, 'Samoa', false, 685);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (186, 'San Marino', false, 378);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (187, 'Sao Tome and Principe', false, 239);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (188, 'Saudi Arabia', false, 966);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (189, 'Senegal', false, 221);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (190, 'Serbia', false, 381);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (191, 'Seychelles', false, 248);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (192, 'Sierra Leone', false, 232);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (193, 'Singapore', false, 65);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (194, 'Sint Maarten', false, 1721);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (195, 'Slovakia', false, 421);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (196, 'Slovenia', false, 386);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (197, 'Solomon Islands', false, 677);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (198, 'Somalia', false, 252);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (199, 'South Africa', false, 27);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (200, 'South Korea', false, 82);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (201, 'South Sudan', false, 211);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (202, 'Spain', true, 34);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (203, 'Sri Lanka', false, 94);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (204, 'Sudan', false, 249);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (205, 'Suriname', false, 597);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (206, 'Svalbard and Jan Mayen', false, 47);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (207, 'Swaziland', false, 268);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (208, 'Sweden', true, 46);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (209, 'Switzerland', true, 41);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (210, 'Syria', false, 963);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (211, 'Taiwan', false, 886);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (212, 'Tajikistan', false, 992);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (213, 'Tanzania', false, 255);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (214, 'Thailand', false, 66);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (215, 'Togo', false, 228);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (216, 'Tokelau', false, 690);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (217, 'Tonga', false, 676);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (218, 'Trinidad and Tobago', false, 1868);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (219, 'Tunisia', false, 216);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (220, 'Turkey', false, 90);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (221, 'Turkmenistan', false, 993);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (222, 'Turks and Caicos Islands', false, 1649);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (223, 'Tuvalu', false, 688);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (224, 'U.S. Virgin Islands', false, 1340);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (225, 'Uganda', false, 256);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (226, 'Ukraine', true, 380);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (227, 'United Arab Emirates', true, 971);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (228, 'United Kingdom', true, 44);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (229, 'United States', true, 1);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (230, 'Uruguay', false, 598);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (231, 'Uzbekistan', false, 998);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (232, 'Vanuatu', false, 678);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (233, 'Vatican', false, 379);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (234, 'Venezuela', false, 58);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (235, 'Vietnam', false, 84);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (236, 'Wallis and Futuna', false, 681);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (237, 'Western Sahara', false, 212);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (238, 'Yemen', false, 967);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (239, 'Zambia', false, 260);
INSERT INTO public.countries (id, countrydesc, topofthelist, phonecountrycode) VALUES (240, 'Zimbabwe', false, 263);

--
-- TOC entry 4362 (class 0 OID 25083)
-- Dependencies: 252
-- Data for Name: documenttypes; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.documenttypes (id, doctypedesc) VALUES (2, 'Title degree');
INSERT INTO public.documenttypes (id, doctypedesc) VALUES (5, 'NDA');
INSERT INTO public.documenttypes (id, doctypedesc) VALUES (6, 'Cost model');
INSERT INTO public.documenttypes (id, doctypedesc) VALUES (7, 'PRL');
INSERT INTO public.documenttypes (id, doctypedesc) VALUES (8, 'Medical apt certificate');
INSERT INTO public.documenttypes (id, doctypedesc) VALUES (1, 'Resume/CV');
INSERT INTO public.documenttypes (id, doctypedesc) VALUES (3, 'Other studies/formation');
INSERT INTO public.documenttypes (id, doctypedesc) VALUES (4, 'Work contract');

--
-- TOC entry 4364 (class 0 OID 25129)
-- Dependencies: 266
-- Data for Name: expensescategories; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.expensescategories (id, categorydesc) VALUES (1, 'Travels');
INSERT INTO public.expensescategories (id, categorydesc) VALUES (2, 'Meals');
INSERT INTO public.expensescategories (id, categorydesc) VALUES (3, 'Lodging');
INSERT INTO public.expensescategories (id, categorydesc) VALUES (6, 'Events');
INSERT INTO public.expensescategories (id, categorydesc) VALUES (7, 'Gas');
INSERT INTO public.expensescategories (id, categorydesc) VALUES (9, 'Office');

--
-- TOC entry 4390 (class 0 OID 25851)
-- Dependencies: 345
-- Data for Name: invoicecurrencies; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.invoicecurrencies (id, code, symbol, label, sortorder) VALUES (1, 'EUR', '€', 'Euro', 0);
INSERT INTO public.invoicecurrencies (id, code, symbol, label, sortorder) VALUES (3, 'USD', '$', 'US Dollar', 1);
INSERT INTO public.invoicecurrencies (id, code, symbol, label, sortorder) VALUES (4, 'CHF', 'Fr', 'Swiss franc', 2);
INSERT INTO public.invoicecurrencies (id, code, symbol, label, sortorder) VALUES (5, 'GBP', '£', 'British Pound Sterling', 3);

--
-- TOC entry 4367 (class 0 OID 25147)
-- Dependencies: 271
-- Data for Name: invoicedocumentcontrols; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (1, 'imgLogoHeader');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (2, 'txtEntityName');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (3, 'txtEntityAddressLine1');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (4, 'txtEntityAddressLine2');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (5, 'txtEntityVAT');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (6, 'txtEmailEntity');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (7, 'txtWebEntity');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (8, 'Cuadro19');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (9, 'InvoiceCode');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (10, 'lblInvoiceCode');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (11, 'InvoiceDate');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (12, 'lblInvoiceDate');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (13, 'txtProjectCode');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (14, 'lblProjectCode');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (15, 'InvoiceDueDate');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (16, 'lblInvoiceDueDate');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (17, 'PurchaseOrder');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (18, 'lblPurchaseOrder');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (21, 'txtInvoiceDataHeader');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (22, 'txtTaxCompName');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (23, 'txtTaxCompAddress');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (24, 'txtTaxCompZipCity');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (25, 'txtTaxCompVAT');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (26, 'Línea20');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (27, 'lblHeaderDescService');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (28, 'lblUnitQty');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (29, 'lblPriceUnit');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (30, 'lblPriceTotal');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (31, 'txtDescriptionService');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (32, 'txtPriceUnit');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (33, 'txtPriceTotal');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (34, 'txtUnitQty');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (35, 'VATAmount');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (36, 'lblVATAmount');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (37, 'Amount');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (38, 'lblAmount');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (39, 'txtTotalInvoice');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (40, 'lblTotal');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (41, 'txtVATExemption');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (42, 'txtBankDetailsHeader');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (43, 'txtBankName');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (44, 'txtBankAddresLine1');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (45, 'txtBankAddresLine2');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (46, 'txtBankAcct');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (47, 'txtBicSwift');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (48, 'txtDipositInfo');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (49, 'txtFooter');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (50, 'txtDisclaimer');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (51, 'strBody');
INSERT INTO public.invoicedocumentcontrols (id, controlname) VALUES (52, 'strSubject');

--
-- TOC entry 4369 (class 0 OID 25151)
-- Dependencies: 273
-- Data for Name: invoicedocumenttext; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (1, 1, 1, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (2, 2, 1, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (3, 3, 1, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (4, 4, 1, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (5, 5, 1, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (6, 6, 1, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (7, 7, 1, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (8, 8, 1, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (9, 9, 1, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (10, 10, 1, '<div>INVOICE NUMBER</div>');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (11, 11, 1, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (12, 12, 1, '<div>INVOICE DATE</div>');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (13, 13, 1, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (14, 14, 1, '<div>INTERNAL PROJECT NUMBER</div>');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (15, 15, 1, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (16, 16, 1, '<div>DUE DATE</div>');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (17, 17, 1, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (18, 18, 1, '<div>PURCHASE ORDER</div>');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (19, 19, 1, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (20, 20, 1, '<div>NUM OC CLIENT</div>');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (21, 21, 1, '<div>INVOICE TO</div>');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (22, 22, 1, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (23, 23, 1, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (24, 24, 1, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (25, 25, 1, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (26, 26, 1, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (27, 27, 1, 'Item/Services provided/Subject');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (28, 28, 1, 'Units');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (29, 29, 1, 'Price per unit');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (30, 30, 1, 'Total');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (31, 31, 1, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (32, 32, 1, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (33, 33, 1, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (34, 34, 1, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (35, 35, 1, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (36, 36, 1, 'VAT 21%');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (37, 37, 1, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (38, 38, 1, 'Total amount');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (39, 39, 1, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (40, 40, 1, 'INVOICE TOTAL');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (41, 41, 1, 'Exempt from VAT pursuant to Article 20.1-9 of Law 37/1992 of 28 December 1992 on Value Added Tax');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (42, 42, 1, '<div>BANK ACCOUNT NUMBER</div>');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (43, 43, 1, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (44, 44, 1, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (45, 45, 1, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (46, 46, 1, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (47, 47, 1, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (48, 48, 1, 'When paying by bank transfer, please state invoice number');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (49, 49, 1, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (50, 1, 2, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (51, 2, 2, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (52, 3, 2, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (53, 4, 2, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (54, 5, 2, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (55, 6, 2, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (56, 7, 2, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (57, 8, 2, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (58, 9, 2, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (59, 10, 2, '<div>FACTURA NUM</div>');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (60, 11, 2, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (61, 12, 2, '<div>FECHA FACTURA</div>');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (62, 13, 2, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (63, 14, 2, '<div>NUM PROYECTO INTERNO</div>');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (64, 15, 2, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (65, 16, 2, '<div>FECHA VENCIMIENTO</div>');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (66, 17, 2, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (67, 18, 2, '<div>PURCHASE ORDER</div>');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (68, 19, 2, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (69, 20, 2, '<div>NUM OC CLIENT</div>');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (70, 21, 2, '<div>DATOS DE FACTURACIÓN DEL CLIENTE</div>');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (71, 22, 2, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (72, 23, 2, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (73, 24, 2, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (74, 25, 2, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (75, 26, 2, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (76, 27, 2, 'Conceptos/Servicios prestados');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (77, 28, 2, 'Unidades');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (78, 29, 2, 'Precio/unidad');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (79, 30, 2, 'Total');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (80, 31, 2, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (81, 32, 2, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (82, 33, 2, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (83, 34, 2, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (84, 35, 2, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (85, 36, 2, 'IVA 21%');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (86, 37, 2, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (87, 38, 2, 'Subtotal');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (88, 39, 2, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (89, 40, 2, 'TOTAL FACTURA');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (90, 41, 2, 'Exento del IVA según el artículo 20.1-9 de la Ley 37/1992, de 28 de diciembre, del Impuesto sobre el Valor Añadido');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (91, 42, 2, '<div>DATOS BANCARIOS</div>');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (92, 43, 2, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (93, 44, 2, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (94, 45, 2, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (95, 46, 2, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (96, 47, 2, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (97, 48, 2, 'Al pagar mediante transferencia bancaria, indique el número de factura');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (98, 49, 2, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (99, 1, 3, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (100, 2, 3, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (101, 3, 3, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (102, 4, 3, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (103, 5, 3, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (104, 6, 3, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (105, 7, 3, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (106, 8, 3, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (107, 9, 3, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (108, 10, 3, '<div>FACTURA NUM</div>');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (109, 11, 3, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (110, 12, 3, '<div>DATA FACTURA</div>');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (111, 13, 3, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (112, 14, 3, '<div>NUM PROJECTE INTERN</div>');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (113, 15, 3, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (114, 16, 3, '<div>DATA VENCIMENT</div>');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (115, 17, 3, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (116, 18, 3, '<div>PURCHASE ORDER</div>');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (117, 19, 3, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (118, 20, 3, '<div>NUM OC CLIENT</div>');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (119, 21, 3, '<div>DADES DE FACTURACIÓ DEL CLIENT</div>');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (120, 22, 3, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (121, 23, 3, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (122, 24, 3, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (123, 25, 3, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (124, 26, 3, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (125, 27, 3, 'Conceptes/Serveis prestats');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (126, 28, 3, 'Unitats');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (127, 29, 3, 'Preu/unitat');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (128, 30, 3, 'Total');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (129, 31, 3, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (130, 32, 3, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (131, 33, 3, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (132, 34, 3, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (133, 35, 3, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (134, 36, 3, 'IVA 21%');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (135, 37, 3, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (136, 38, 3, 'Subtotal');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (137, 39, 3, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (138, 40, 3, 'TOTAL FACTURA');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (139, 41, 3, 'Exempta d’IVA segons l’article 20.1-9 de la llei 37/1992 del 28 de desembre de 1992, de l’Impost sobre el Valor Afegit');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (140, 42, 3, '<div>DADES BANCÀRIES</div>');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (141, 43, 3, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (142, 44, 3, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (143, 45, 3, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (144, 46, 3, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (145, 47, 3, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (146, 48, 3, 'Quan pagueu per transferència bancària, indiqueu el número de factura');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (147, 49, 3, NULL);
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (148, 50, 1, 'Please be aware that your bank may deduct a fee or a percentage for international bank payments. The net amount to be received by HiTT should be in accordance with the total amount of this invoice. Thank you for you collaboration.');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (149, 50, 2, 'Tenga en cuenta que su banco podría deducir una comisión o un porcentaje por pagos internacionales. El importe neto que recibirá HiTT deberá coincidir con el importe total de esta factura. Gracias por su colaboración.');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (150, 50, 3, 'Tingueu en compte que el vostre banc pot deduir una comissió o un percentatge per pagaments bancaris internacionals. L''import net que rebrà HiTT hauria d''estar d''acord amb l''import total d''aquesta factura. Gràcies per la vostra col·laboració.');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (151, 51, 1, '<div>Good morning, I am sending the invoice number &#123;InvoiceCode&#125; regarding to our last conversation.</div>');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (152, 51, 2, '<div>Buenos días, Adjunto factura número &#123;InvoiceCode&#125; según nuestra última conversación</div>');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (153, 51, 3, '<div>Bon dia, Adjunt factura número &#123;InvoiceCode&#125; segons la nostra darrera conversa</div>');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (154, 52, 1, '<div>[&#123;Entity&#125;] New invoice</div>');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (155, 52, 2, '<div><font color="black">[&#123;Entity&#125;] Nueva factura</font></div>');
INSERT INTO public.invoicedocumenttext (id, controlnameid, languageid, languagetext) VALUES (156, 52, 3, '<div><font color="black">[&#123;Entity&#125;] Nova factura</font></div>');

--
-- TOC entry 4371 (class 0 OID 25163)
-- Dependencies: 275
-- Data for Name: invoicepaymentmethods; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.invoicepaymentmethods (id, methoddesc) VALUES (1, 'Email');
INSERT INTO public.invoicepaymentmethods (id, methoddesc) VALUES (2, 'e-Fact');
INSERT INTO public.invoicepaymentmethods (id, methoddesc) VALUES (3, 'B2BRouter');
INSERT INTO public.invoicepaymentmethods (id, methoddesc) VALUES (4, 'Customer-owned platform');

--
-- TOC entry 4373 (class 0 OID 25171)
-- Dependencies: 279
-- Data for Name: invoices_vattypes; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.invoices_vattypes (id, percentage, disclaimer_es, disclaimer_ca, disclaimer_en, vatdescription_short_es, vatdescription_short_ca, vatdescription_short_en) VALUES (1, 0, 'Exento del IVA según el artículo 20.1-9 de la Ley 37/1992, de 28 de diciembre, del Impuesto sobre el Valor Añadido', 'Exempta d’IVA segons l’article 20.1-9 de la llei 37/1992 del 28 de desembre de 1992, de l’Impost sobre el Valor Afegit', 'Exempt from VAT pursuant to Article 20.1-9 of Law 37/1992 of 28 December 1992 on Value Added Tax', 'IVA para educación', 'IVA per a l''educació', 'VAT for education');
INSERT INTO public.invoices_vattypes (id, percentage, disclaimer_es, disclaimer_ca, disclaimer_en, vatdescription_short_es, vatdescription_short_ca, vatdescription_short_en) VALUES (2, 0, 'Operación intracomunitaria. Inversión del sujeto pasivo (art. 84.Uno.2º LIVA)', 'Operació intracomunitària. Inversió del subjecte passiu (art. 84.U.2º LIVA)', 'EU transaction. Reverse charge mechanism (Art. 84.One.2º VAT Law)', 'IVA Intracomunitario', 'IVA Intracomunitari', 'EU VAT');
INSERT INTO public.invoices_vattypes (id, percentage, disclaimer_es, disclaimer_ca, disclaimer_en, vatdescription_short_es, vatdescription_short_ca, vatdescription_short_en) VALUES (3, 0, 'Operación no sujeta por regla de localización (art. 69 y 70 LIVA)', 'Operació no subjecta per regla de localització (art. 69 i 70 LIVA)', 'Transaction not subject to location rule (art. 69 and 70 LIVA)', 'IVA Extracomunitario', 'IVA Extracomunitari', 'Non EU VAT');
INSERT INTO public.invoices_vattypes (id, percentage, disclaimer_es, disclaimer_ca, disclaimer_en, vatdescription_short_es, vatdescription_short_ca, vatdescription_short_en) VALUES (4, 21, NULL, NULL, NULL, 'IVA regular', 'IVA regular', 'Regular VAT');

--
-- TOC entry 4375 (class 0 OID 25177)
-- Dependencies: 281
-- Data for Name: invoicescheduletypes; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.invoicescheduletypes (id, scheduledesc, defaultvalue) VALUES (1, 'Once', 1);
INSERT INTO public.invoicescheduletypes (id, scheduledesc, defaultvalue) VALUES (3, 'Recurrent', 6);
INSERT INTO public.invoicescheduletypes (id, scheduledesc, defaultvalue) VALUES (2, 'Start - End', 2);

--
-- TOC entry 4377 (class 0 OID 25193)
-- Dependencies: 285
-- Data for Name: invoicesstatus; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.invoicesstatus (id, statusdesc) VALUES (1, 'Pending PO');
INSERT INTO public.invoicesstatus (id, statusdesc) VALUES (2, 'Not generated');
INSERT INTO public.invoicesstatus (id, statusdesc) VALUES (3, 'To be sent');
INSERT INTO public.invoicesstatus (id, statusdesc) VALUES (4, 'Sent to customer');
INSERT INTO public.invoicesstatus (id, statusdesc) VALUES (5, 'Collected');
INSERT INTO public.invoicesstatus (id, statusdesc) VALUES (6, 'Cancelled');
INSERT INTO public.invoicesstatus (id, statusdesc) VALUES (7, 'No invoice');

--
-- TOC entry 4379 (class 0 OID 25207)
-- Dependencies: 289
-- Data for Name: languages; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.languages (id, languagedesc) VALUES (1, 'English');
INSERT INTO public.languages (id, languagedesc) VALUES (2, 'Spanish');
INSERT INTO public.languages (id, languagedesc) VALUES (3, 'Catalan');

--
-- TOC entry 4381 (class 0 OID 25217)
-- Dependencies: 291
-- Data for Name: loglevels; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.loglevels (id, logleveldesc) VALUES (1, 'Debug');
INSERT INTO public.loglevels (id, logleveldesc) VALUES (2, 'Error');
INSERT INTO public.loglevels (id, logleveldesc) VALUES (3, 'Warning');
INSERT INTO public.loglevels (id, logleveldesc) VALUES (4, 'Information');

--
-- TOC entry 4383 (class 0 OID 25282)
-- Dependencies: 308
-- Data for Name: projectstatus; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.projectstatus (id, projectstatusdesc, ordinal) VALUES (2, 'WIP', 5);
INSERT INTO public.projectstatus (id, projectstatusdesc, ordinal) VALUES (4, 'Delivered', 6);
INSERT INTO public.projectstatus (id, projectstatusdesc, ordinal) VALUES (5, 'Lead', 1);
INSERT INTO public.projectstatus (id, projectstatusdesc, ordinal) VALUES (6, 'Cancelled', 9);
INSERT INTO public.projectstatus (id, projectstatusdesc, ordinal) VALUES (7, 'Closed', 8);
INSERT INTO public.projectstatus (id, projectstatusdesc, ordinal) VALUES (8, 'Oferta', 2);
INSERT INTO public.projectstatus (id, projectstatusdesc, ordinal) VALUES (9, 'Guanyat', 3);

--
-- TOC entry 4385 (class 0 OID 25296)
-- Dependencies: 312
-- Data for Name: projecttypes; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.projecttypes (id, projecttypedesc) VALUES (1, 'HiTT _ Consulting');
INSERT INTO public.projecttypes (id, projecttypedesc) VALUES (2, 'HiTT _ Development');
INSERT INTO public.projecttypes (id, projecttypedesc) VALUES (3, 'HiTT _ Academy');
INSERT INTO public.projecttypes (id, projecttypedesc) VALUES (4, 'FHiTT _ Supporting Innovation');
INSERT INTO public.projecttypes (id, projecttypedesc) VALUES (5, 'FHiTT _ Boosting co-creation');
INSERT INTO public.projecttypes (id, projecttypedesc) VALUES (6, 'FHiTT _Internal R&D');
INSERT INTO public.projecttypes (id, projecttypedesc) VALUES (7, 'FHiTT _ Academy');
INSERT INTO public.projecttypes (id, projecttypedesc) VALUES (8, 'OSM_TC');
INSERT INTO public.projecttypes (id, projecttypedesc) VALUES (9, 'OSM_Advisory Board');
INSERT INTO public.projecttypes (id, projecttypedesc) VALUES (10, 'OSM_Survey');
INSERT INTO public.projecttypes (id, projecttypedesc) VALUES (11, 'OSM_Project');
INSERT INTO public.projecttypes (id, projecttypedesc) VALUES (12, 'OSM_Survey + TC');
INSERT INTO public.projecttypes (id, projecttypedesc) VALUES (13, 'Others');

--
-- TOC entry 4387 (class 0 OID 25348)
-- Dependencies: 318
-- Data for Name: timeoffworkflowstatus; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.timeoffworkflowstatus (id, workflowstatusdesc) VALUES (1, 'Not submitted');
INSERT INTO public.timeoffworkflowstatus (id, workflowstatusdesc) VALUES (2, 'Submitted');
INSERT INTO public.timeoffworkflowstatus (id, workflowstatusdesc) VALUES (3, 'Pending approval');
INSERT INTO public.timeoffworkflowstatus (id, workflowstatusdesc) VALUES (4, 'Approved');
INSERT INTO public.timeoffworkflowstatus (id, workflowstatusdesc) VALUES (5, 'Rejected');
INSERT INTO public.timeoffworkflowstatus (id, workflowstatusdesc) VALUES (6, 'Withdrawn');
INSERT INTO public.timeoffworkflowstatus (id, workflowstatusdesc) VALUES (7, 'Cancelled');

--
-- TOC entry 4396 (class 0 OID 0)
-- Dependencies: 239
-- Name: biotechspectrums_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.biotechspectrums_id_seq', 7, false);

--
-- TOC entry 4397 (class 0 OID 0)
-- Dependencies: 245
-- Name: companytypes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.companytypes_id_seq', 12, false);

--
-- TOC entry 4398 (class 0 OID 0)
-- Dependencies: 251
-- Name: countries_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.countries_id_seq', 241, false);

--
-- TOC entry 4399 (class 0 OID 0)
-- Dependencies: 253
-- Name: documenttypes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.documenttypes_id_seq', 8, true);

--
-- TOC entry 4400 (class 0 OID 0)
-- Dependencies: 267
-- Name: expensescategories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.expensescategories_id_seq', 10, false);

--
-- TOC entry 4401 (class 0 OID 0)
-- Dependencies: 344
-- Name: invoicecurrencies_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.invoicecurrencies_id_seq', 26, true);

--
-- TOC entry 4402 (class 0 OID 0)
-- Dependencies: 272
-- Name: invoicedocumentcontrols_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.invoicedocumentcontrols_id_seq', 53, false);

--
-- TOC entry 4403 (class 0 OID 0)
-- Dependencies: 274
-- Name: invoicedocumenttext_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.invoicedocumenttext_id_seq', 157, false);

--
-- TOC entry 4404 (class 0 OID 0)
-- Dependencies: 276
-- Name: invoicepaymentmethods_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.invoicepaymentmethods_id_seq', 5, false);

--
-- TOC entry 4405 (class 0 OID 0)
-- Dependencies: 280
-- Name: invoices_vattypes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.invoices_vattypes_id_seq', 4, true);

--
-- TOC entry 4406 (class 0 OID 0)
-- Dependencies: 282
-- Name: invoicescheduletypes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.invoicescheduletypes_id_seq', 4, false);

--
-- TOC entry 4407 (class 0 OID 0)
-- Dependencies: 286
-- Name: invoicesstatus_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.invoicesstatus_id_seq', 8, false);

--
-- TOC entry 4408 (class 0 OID 0)
-- Dependencies: 290
-- Name: languages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.languages_id_seq', 4, false);

--
-- TOC entry 4409 (class 0 OID 0)
-- Dependencies: 292
-- Name: loglevels_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.loglevels_id_seq', 5, false);

--
-- TOC entry 4410 (class 0 OID 0)
-- Dependencies: 309
-- Name: projectstatus_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.projectstatus_id_seq', 10, false);

--
-- TOC entry 4411 (class 0 OID 0)
-- Dependencies: 313
-- Name: projecttypes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.projecttypes_id_seq', 14, false);

--
-- TOC entry 4412 (class 0 OID 0)
-- Dependencies: 326
-- Name: timeoffworkflowstatus_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.timeoffworkflowstatus_id_seq', 8, false);

-- Completed on 2026-09-02 12:05:14

--
-- PostgreSQL database dump complete
--


