-- ==========================================================================
-- REFERENCE DATA — lookup rows every Ops instance needs
-- --------------------------------------------------------------------------
-- >>> PLACEHOLDER. Populate from test_ops once, review, commit. <<<
--
-- A fresh instance's schema (the 0C baseline) has EMPTY tables. Without this
-- data there are no project statuses, countries, currencies, VAT types, or
-- invoice-PDF field labels, and the app is unusable.
--
-- Generate (Windows PowerShell / any shell — put the password in PGPASSWORD,
-- not the URL, to avoid quoting issues):
--
--   $env:PGPASSWORD = "..."
--   pg_dump --data-only --no-owner --column-inserts `
--     --table=public.countries --table=public.languages `
--     --table=public.loglevels --table=public.documenttypes `
--     --table=public.companytypes --table=public.biotechspectrums `
--     --table=public.projecttypes --table=public.projectstatus `
--     --table=public.invoicesstatus --table=public.invoicepaymentmethods `
--     --table=public.invoicescheduletypes --table=public.invoices_vattypes `
--     --table=public.invoicecurrencies --table=public.timeoffworkflowstatus `
--     --table=public.expensescategories --table=public.invoicedocumentcontrols `
--     --table=public.invoicedocumenttext --table=public.global_settings `
--     -h 217.154.101.149 -p 8432 -U postgres -d test_ops `
--     > provision/seed/reference-data.sql
--
-- REVIEW before committing — this ships to every customer:
--   - no real employee / business-partner / project / invoice rows
--   - projectstatus / invoices_vattypes carry Catalan/Spanish text and
--     Spanish VAT law disclaimers — fine as a default (customers rename in
--     Settings), but know it's there
--   - global_settings may hold HITT-specific paths (OneDrive, etc.) — grep
--     it and drop or blank those rows
--   - biotechspectrums is HITT's domain taxonomy — harmless to ship, or drop
--     the --table for it if you'd rather start empty
--
-- provision.js loads this into the fresh DB, then runs seed-instance.sql and
-- fix-sequences.sql. Replace everything below with the dump output.
-- ==========================================================================

-- (reference data goes here)
