/**
 * /api/expenses
 * ---------------------------------------------------------------------------
 * Company expense records — meals with customers, hotels, flights, car
 * rentals, materials, etc. Most are bound to a project; internal expenses
 * (water supply, employee amenities, …) have no project and are flagged
 * isinternal.
 *
 * CRUD + bulk edit/delete, plus one optional evidence document per expense
 * (image or PDF), stored on the API host under UPLOAD_DIR (never in the
 * repo — see .gitignore) and streamed back through GET /:id/document.
 *
 * New table, created idempotently at runtime (mirrored in
 * server/db/schema-changes.sql):  companyexpenses
 * ---------------------------------------------------------------------------
 */
const path = require("path");
const fs = require("fs");
const crypto = require("crypto");
const express = require("express");
const multer = require("multer");
const { pool } = require("../config/db");
const { requireModuleAccess } = require("../lib/permissions");
const { logAudit } = require("../lib/audit");

const router = express.Router();
router.use(requireModuleAccess("expenses"));

const UPLOAD_DIR = process.env.UPLOAD_DIR
  ? path.resolve(process.env.UPLOAD_DIR, "expenses")
  : path.join(__dirname, "..", "uploads", "expenses");
fs.mkdirSync(UPLOAD_DIR, { recursive: true });

const ALLOWED_MIME = new Set([
  "application/pdf",
  "image/jpeg", "image/png", "image/gif", "image/webp", "image/heic", "image/heif",
]);

const upload = multer({
  storage: multer.diskStorage({
    destination: (req, file, cb) => cb(null, UPLOAD_DIR),
    filename: (req, file, cb) => {
      const ext = path.extname(file.originalname || "").slice(0, 12).replace(/[^.\w]/g, "");
      cb(null, `${crypto.randomUUID()}${ext}`);
    },
  }),
  limits: { fileSize: 15 * 1024 * 1024, files: 1 },
  fileFilter: (req, file, cb) =>
    ALLOWED_MIME.has(file.mimetype) ? cb(null, true) : cb(new Error("Only images or PDF files are allowed.")),
});

// Wrap multer so its errors come back as clean JSON. A JSON request (no
// file) passes straight through.
const acceptDocument = (req, res, next) =>
  upload.single("document")(req, res, (err) => {
    if (err) return res.status(400).json({ error: "upload_error", message: err.message });
    next();
  });

function removeFileQuietly(storedName) {
  if (!storedName) return;
  fs.promises.unlink(path.join(UPLOAD_DIR, path.basename(storedName))).catch(() => {});
}

let schemaReady = null;
function ensureSchema() {
  if (!schemaReady) {
    schemaReady = pool
      .query(`
        CREATE TABLE IF NOT EXISTS public.companyexpenses (
          id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          expensedate  date,
          category     varchar(64),
          description  text,
          amount       numeric(12,2),
          currency     varchar(8) DEFAULT 'EUR',
          projectid    bigint,
          isinternal   boolean DEFAULT false,
          paidby       bigint,
          documentpath text,
          documentname varchar(255),
          documentmime varchar(100),
          createdat    timestamp without time zone DEFAULT now(),
          createdby    bigint,
          updatedat    timestamp without time zone,
          updatedby    bigint
        )
      `)
      .then(() => pool.query(`CREATE INDEX IF NOT EXISTS companyexpenses_projectid_idx ON public.companyexpenses (projectid)`))
      .then(() => pool.query(`CREATE INDEX IF NOT EXISTS companyexpenses_date_idx ON public.companyexpenses (expensedate DESC)`))
      .catch((err) => { schemaReady = null; throw err; });
  }
  return schemaReady;
}

const num = (v) => (v === "" || v == null || Number.isNaN(Number(v)) ? null : Number(v));
const bool = (v) => v === true || v === "true" || v === "1" || v === 1;

// Shared body shape for POST/PATCH — works for multipart (string values)
// and JSON alike.
function expenseBody(req) {
  const b = req.body || {};
  const isInternal = bool(b.isInternal);
  return {
    expenseDate: b.expenseDate || null,
    category: (b.category || "").trim() || null,
    description: (b.description || "").trim() || null,
    amount: num(b.amount),
    currency: ((b.currency || "EUR").trim().slice(0, 8)) || "EUR",
    projectId: isInternal ? null : num(b.projectId),
    isInternal,
    paidBy: num(b.paidBy),
  };
}

const EXPENSE_SELECT = `
  SELECT x.id, x.expensedate AS "expenseDate", x.category, x.description,
         x.amount, x.currency, x.isinternal AS "isInternal",
         x.projectid AS "projectId", p.projectnumber AS "projectCode", p.projectname AS "projectName",
         x.paidby AS "paidById",
         NULLIF(TRIM(CONCAT(e.employeefirstname, ' ', e.employeelastname)), '') AS "paidByName",
         (x.documentpath IS NOT NULL) AS "hasDocument", x.documentname AS "documentName", x.documentmime AS "documentMime",
         x.createdat AS "createdAt", x.updatedat AS "updatedAt"
  FROM companyexpenses x
  LEFT JOIN projects p ON p.id = x.projectid
  LEFT JOIN employees e ON e.id = x.paidby
`;

async function expenseRow(id) {
  const { rows } = await pool.query(`${EXPENSE_SELECT} WHERE x.id = $1`, [id]);
  return rows[0] || null;
}

/* ============================== LIST ================================== */
// GET /api/expenses?search=&projectId=&category=&scope=&startDate=&endDate=&page=&limit=
router.get("/", async (req, res) => {
  try {
    await ensureSchema();
    const { search, projectId, category, scope, startDate, endDate } = req.query;
    const limit = Math.min(Number(req.query.limit) || 50, 500);
    const page = Math.max(Number(req.query.page) || 1, 1);
    const offset = (page - 1) * limit;

    const where = [];
    const filterParams = [];
    const P = (v) => { filterParams.push(v); return `$${filterParams.length}`; };

    if (search) {
      const t = P(search);
      where.push(`(x.description ILIKE '%'||${t}||'%' OR x.category ILIKE '%'||${t}||'%'
                   OR p.projectnumber ILIKE '%'||${t}||'%' OR p.projectname ILIKE '%'||${t}||'%')`);
    }
    if (projectId) where.push(`x.projectid = ${P(projectId)}::bigint`);
    if (category) where.push(`x.category = ${P(category)}`);
    if (scope === "internal") where.push("x.isinternal IS TRUE");
    if (scope === "project") where.push("x.isinternal IS NOT TRUE");
    if (startDate) where.push(`x.expensedate >= ${P(startDate)}::date`);
    if (endDate) where.push(`x.expensedate <= ${P(endDate)}::date`);

    const whereSql = where.length ? `WHERE ${where.join(" AND ")}` : "";

    const listParams = [...filterParams, limit, offset];
    const { rows } = await pool.query(
      `${EXPENSE_SELECT}, COUNT(*) OVER() AS "totalCount"
       ${whereSql}
       ORDER BY x.expensedate DESC NULLS LAST, x.id DESC
       LIMIT $${filterParams.length + 1} OFFSET $${filterParams.length + 2}`,
      listParams
    );
    const total = rows.length ? Number(rows[0].totalCount) : 0;

    const sumRes = await pool.query(
      `SELECT COALESCE(SUM(x.amount), 0) AS total
       FROM companyexpenses x LEFT JOIN projects p ON p.id = x.projectid
       ${whereSql}`,
      filterParams
    );

    res.json({
      rows: rows.map(({ totalCount, ...r }) => r),
      total, page, limit,
      sum: Number(sumRes.rows[0].total),
    });
  } catch (err) {
    console.error("[GET /api/expenses] DB error:", err.message);
    res.status(502).json({ error: "database_unreachable", message: err.message });
  }
});

// GET /api/expenses/categories — the defaults plus anything already used.
router.get("/categories", async (req, res) => {
  try {
    await ensureSchema();
    const { rows } = await pool.query(
      `SELECT DISTINCT category FROM companyexpenses WHERE category IS NOT NULL AND category <> '' ORDER BY category`
    );
    const defaults = [
      "Meals with customers", "Hotel", "Flight tickets", "Car rental",
      "Taxi / transport", "Materials", "Software / licences", "Internal", "Other",
    ];
    res.json([...new Set([...defaults, ...rows.map((r) => r.category)])]);
  } catch (err) {
    console.error("[GET /api/expenses/categories] DB error:", err.message);
    res.status(502).json({ error: "database_unreachable", message: err.message });
  }
});

/* ============================== CREATE / EDIT ========================= */
router.post("/", acceptDocument, async (req, res) => {
  try {
    await ensureSchema();
    const b = expenseBody(req);
    if (b.amount == null) {
      removeFileQuietly(req.file?.filename);
      return res.status(400).json({ error: "validation_error", message: "An amount is required." });
    }
    const { rows } = await pool.query(
      `INSERT INTO companyexpenses
         (expensedate, category, description, amount, currency, projectid, isinternal, paidby,
          documentpath, documentname, documentmime, createdat, createdby)
       VALUES ($1::date, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, now(), $12)
       RETURNING id`,
      [
        b.expenseDate, b.category, b.description, b.amount, b.currency, b.projectId, b.isInternal, b.paidBy,
        req.file?.filename ?? null,
        req.file ? (req.file.originalname || "").slice(0, 255) : null,
        req.file?.mimetype ?? null,
        req.hittUser?.employeeId || null,
      ]
    );
    const row = await expenseRow(rows[0].id);
    res.status(201).json(row);
    logAudit(req, {
      kind: "expense.create",
      desc: `Added expense${b.category ? ` (${b.category})` : ""} ${b.currency} ${b.amount}` +
        (row.projectCode ? ` on project ${row.projectCode}` : b.isInternal ? " (internal)" : ""),
    });
  } catch (err) {
    removeFileQuietly(req.file?.filename);
    console.error("[POST /api/expenses] DB error:", err.message);
    res.status(502).json({ error: "database_unreachable", message: err.message });
  }
});

router.patch("/:id", acceptDocument, async (req, res) => {
  try {
    await ensureSchema();
    const { rows: curRows } = await pool.query(
      `SELECT documentpath, category FROM companyexpenses WHERE id = $1`, [req.params.id]
    );
    if (!curRows.length) {
      removeFileQuietly(req.file?.filename);
      return res.status(404).json({ error: "not_found", message: "Expense not found." });
    }
    const oldDoc = curRows[0].documentpath;
    const b = expenseBody(req);
    if (b.amount == null) {
      removeFileQuietly(req.file?.filename);
      return res.status(400).json({ error: "validation_error", message: "An amount is required." });
    }

    await pool.query(
      `UPDATE companyexpenses SET
         expensedate = $1::date, category = $2, description = $3, amount = $4, currency = $5,
         projectid = $6, isinternal = $7, paidby = $8,
         documentpath = COALESCE($9, documentpath),
         documentname = COALESCE($10, documentname),
         documentmime = COALESCE($11, documentmime),
         updatedat = now(), updatedby = $12
       WHERE id = $13`,
      [
        b.expenseDate, b.category, b.description, b.amount, b.currency, b.projectId, b.isInternal, b.paidBy,
        req.file?.filename ?? null,
        req.file ? (req.file.originalname || "").slice(0, 255) : null,
        req.file?.mimetype ?? null,
        req.hittUser?.employeeId || null, req.params.id,
      ]
    );
    if (req.file && oldDoc && oldDoc !== req.file.filename) removeFileQuietly(oldDoc);

    const row = await expenseRow(req.params.id);
    res.json(row);
    logAudit(req, {
      kind: req.file ? "expense.document" : "expense.update",
      desc: `${req.file ? "Replaced the evidence on" : "Edited"} expense #${req.params.id}` +
        (row.category ? ` (${row.category})` : ""),
    });
  } catch (err) {
    removeFileQuietly(req.file?.filename);
    console.error("[PATCH /api/expenses/:id] DB error:", err.message);
    res.status(502).json({ error: "database_unreachable", message: err.message });
  }
});

router.delete("/:id", async (req, res) => {
  try {
    await ensureSchema();
    const { rows } = await pool.query(
      `DELETE FROM companyexpenses WHERE id = $1 RETURNING documentpath, category`, [req.params.id]
    );
    if (!rows.length) return res.status(404).json({ error: "not_found", message: "Expense not found." });
    removeFileQuietly(rows[0].documentpath);
    res.status(204).end();
    logAudit(req, { kind: "expense.delete", desc: `Deleted expense #${req.params.id}${rows[0].category ? ` (${rows[0].category})` : ""}` });
  } catch (err) {
    console.error("[DELETE /api/expenses/:id] DB error:", err.message);
    res.status(502).json({ error: "database_unreachable", message: err.message });
  }
});

/* ============================== BULK ================================= */
// POST /api/expenses/bulk  { action: 'delete' | 'update', ids: [...], patch: {...} }
router.post("/bulk", async (req, res) => {
  const { action, ids, patch } = req.body || {};
  const idList = Array.isArray(ids) ? ids.map(Number).filter(Number.isInteger) : [];
  if (!idList.length) return res.status(400).json({ error: "validation_error", message: "No expenses selected." });

  try {
    await ensureSchema();
    if (action === "delete") {
      const { rows } = await pool.query(
        `DELETE FROM companyexpenses WHERE id = ANY($1::bigint[]) RETURNING documentpath`, [idList]
      );
      rows.forEach((r) => removeFileQuietly(r.documentpath));
      res.json({ affected: rows.length });
      logAudit(req, { kind: "expense.bulk", desc: `Bulk-deleted ${rows.length} expense(s)` });
      return;
    }
    if (action === "update") {
      const p = patch || {};
      const sets = [];
      const params = [];
      const set = (sql, val) => { params.push(val); sets.push(sql.replace("?", `$${params.length}`)); };

      if (p.category !== undefined) set("category = ?", (p.category || "").trim() || null);
      if (p.projectId !== undefined || p.isInternal !== undefined) {
        const internal = bool(p.isInternal);
        set("isinternal = ?", internal);
        set("projectid = ?", internal ? null : num(p.projectId));
      }
      if (p.paidBy !== undefined) set("paidby = ?", num(p.paidBy));
      if (p.expenseDate !== undefined) set("expensedate = ?::date", p.expenseDate || null);
      if (!sets.length) return res.status(400).json({ error: "validation_error", message: "Nothing to update." });

      set("updatedby = ?", req.hittUser?.employeeId || null);
      sets.push("updatedat = now()");
      params.push(idList);
      const { rowCount } = await pool.query(
        `UPDATE companyexpenses SET ${sets.join(", ")} WHERE id = ANY($${params.length}::bigint[])`, params
      );
      res.json({ affected: rowCount });
      logAudit(req, { kind: "expense.bulk", desc: `Bulk-updated ${rowCount} expense(s)` });
      return;
    }
    res.status(400).json({ error: "validation_error", message: "action must be 'delete' or 'update'." });
  } catch (err) {
    console.error("[POST /api/expenses/bulk] DB error:", err.message);
    res.status(502).json({ error: "database_unreachable", message: err.message });
  }
});

/* ============================== DOCUMENT ============================= */
// GET /api/expenses/:id/document — stream the evidence inline.
router.get("/:id/document", async (req, res) => {
  try {
    await ensureSchema();
    const { rows } = await pool.query(
      `SELECT documentpath, documentname, documentmime FROM companyexpenses WHERE id = $1`, [req.params.id]
    );
    if (!rows.length || !rows[0].documentpath) return res.status(404).json({ error: "not_found" });
    const abs = path.join(UPLOAD_DIR, path.basename(rows[0].documentpath));
    if (!fs.existsSync(abs)) return res.status(404).json({ error: "not_found", message: "File missing on disk." });
    res.setHeader("Content-Type", rows[0].documentmime || "application/octet-stream");
    res.setHeader("Content-Disposition", `inline; filename="${(rows[0].documentname || "evidence").replace(/["\r\n]/g, "")}"`);
    fs.createReadStream(abs).pipe(res);
  } catch (err) {
    console.error("[GET /api/expenses/:id/document] error:", err.message);
    res.status(502).json({ error: "server_error", message: err.message });
  }
});

// DELETE /api/expenses/:id/document — remove the evidence file + refs.
router.delete("/:id/document", async (req, res) => {
  try {
    await ensureSchema();
    const { rows } = await pool.query(`SELECT documentpath FROM companyexpenses WHERE id = $1`, [req.params.id]);
    if (!rows.length) return res.status(404).json({ error: "not_found" });
    await pool.query(
      `UPDATE companyexpenses SET documentpath = NULL, documentname = NULL, documentmime = NULL,
         updatedat = now(), updatedby = $2 WHERE id = $1`,
      [req.params.id, req.hittUser?.employeeId || null]
    );
    removeFileQuietly(rows[0].documentpath);
    res.status(204).end();
    logAudit(req, { kind: "expense.document", desc: `Removed the evidence from expense #${req.params.id}` });
  } catch (err) {
    console.error("[DELETE /api/expenses/:id/document] error:", err.message);
    res.status(502).json({ error: "server_error", message: err.message });
  }
});

module.exports = router;
