-- ==========================================================================
-- BASELINE — full Ops schema as of v0.2.x
-- Generated from a pg_dump --schema-only of test_ops by
-- server/scripts/sanitize-baseline.js. See docs/migrations.md.
--
-- A database that ALREADY has this schema (HITT, or any instance created
-- before migrations) must NOT run this — mark it applied instead:
--   INSERT INTO pgmigrations (name, run_on)
--   VALUES ('1756684800000_baseline', now());
-- ==========================================================================

CREATE FUNCTION public.set_new_invoice_status(inv_date date, inv_sent_date date, inv_diposit_date date) RETURNS integer
    LANGUAGE plpgsql
    AS $$
BEGIN
    -- Check all three dates are NULL or empty
    IF inv_date IS NULL AND inv_sent_date IS NULL AND inv_diposit_date IS NULL THEN
        RETURN 2; -- E_InvStatus.NOTGENERATED
    
    -- Check if only InvoiceDate is provided
    ELSIF inv_date IS NOT NULL AND inv_sent_date IS NULL AND inv_diposit_date IS NULL THEN
        RETURN 3; -- E_InvStatus.TOBESENT
    
    -- Check if InvoiceDate and InvoiceSentDate are provided, but not InvoiceDipositDate
    ELSIF inv_date IS NOT NULL AND inv_sent_date IS NOT NULL AND inv_diposit_date IS NULL THEN
        RETURN 4; -- E_InvStatus.SENTTOCUSTOMER
    
    -- Check if all three dates are provided
    ELSIF inv_date IS NOT NULL AND inv_sent_date IS NOT NULL AND inv_diposit_date IS NOT NULL THEN
        RETURN 5; -- E_InvStatus.COLLECTED
    
    -- Default case (equivalent to Else in VBA)
    ELSE
        RETURN 1; -- E_InvStatus.PENDING_PO
    END IF;
END;
$$;

CREATE TABLE public.actionsaudit (
    id bigint NOT NULL,
    actionuserid bigint,
    actiondesc text,
    actionts timestamp without time zone,
    actioncomputer character varying(255),
    actionenvironment character varying(255),
    loglevel bigint,
    actionusername character varying(255),
    actionkind character varying(64),
    actionip character varying(64)
);

ALTER TABLE public.actionsaudit ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public."actionsaudit_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.addresses (
    id bigint NOT NULL,
    businesspartnerid double precision,
    streetname character varying(255),
    city character varying(255),
    state character varying(255),
    zipcode character varying(255),
    phonenumber character varying(255),
    phonenumber2 character varying(255),
    countryid double precision
);

ALTER TABLE public.addresses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.addresses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.admins (
    id bigint NOT NULL,
    employeeid bigint NOT NULL,
    grantedat timestamp without time zone DEFAULT now(),
    grantedby bigint
);

CREATE SEQUENCE public.admins_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.admins_id_seq OWNED BY public.admins.id;

CREATE TABLE public.appconfig (
    configkey character varying(64) NOT NULL,
    configvalue text,
    updatedat timestamp without time zone,
    updatedby bigint
);

CREATE TABLE public.bankaccts (
    id bigint NOT NULL,
    bicswift character varying(255),
    iban character varying(255),
    entityid bigint,
    acctid bigint,
    bankname character varying(255),
    bankaddrline1 character varying(255),
    bankaddrline2 character varying(255)
);

ALTER TABLE public.bankaccts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bankaccts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.biotechspectrums (
    id bigint NOT NULL,
    spectrumdesc character varying(255)
);

ALTER TABLE public.biotechspectrums ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.biotechspectrums_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.businesspartnerchangelog (
    id bigint NOT NULL,
    businesspartnerid bigint NOT NULL,
    changedat timestamp with time zone DEFAULT now() NOT NULL,
    changedby bigint,
    summary text NOT NULL
);

CREATE SEQUENCE public.businesspartnerchangelog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.businesspartnerchangelog_id_seq OWNED BY public.businesspartnerchangelog.id;

CREATE TABLE public.businesspartners (
    id bigint NOT NULL,
    bpname character varying(255),
    finsitcode character varying(255),
    entityid double precision,
    webpage character varying(255),
    importid double precision,
    companytypeid bigint,
    languageid bigint,
    lastupdated timestamp with time zone,
    lastupdatedby bigint
);

ALTER TABLE public.businesspartners ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.businesspartners_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.businesspartnersnotes (
    id bigint NOT NULL,
    notes text,
    usernoteid double precision,
    commentsts timestamp without time zone,
    bpid double precision,
    dumpid integer,
    employeeid bigint
);

ALTER TABLE public.businesspartnersnotes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.businesspartnersnotes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.companytypes (
    id bigint NOT NULL,
    companytypedesc character varying(255)
);

ALTER TABLE public.companytypes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.companytypes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.contacts (
    id bigint NOT NULL,
    contactname character varying(255),
    "position" character varying(255),
    emailaddress character varying(255),
    phonenumber character varying(255),
    businesspartnerid double precision,
    dumpid integer
);

ALTER TABLE public.contacts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contacts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.corporateworkcalendar (
    id bigint NOT NULL,
    workyear double precision,
    labourhoursperyear double precision,
    holidaysamount double precision,
    corporateholidaysamount double precision,
    updatedat timestamp without time zone,
    updatedby double precision
);

ALTER TABLE public.corporateworkcalendar ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.corporateworkcalendar_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.countries (
    id bigint NOT NULL,
    countrydesc character varying(255),
    topofthelist boolean,
    phonecountrycode double precision
);

ALTER TABLE public.countries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.countries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.documenttypes (
    id bigint NOT NULL,
    doctypedesc character varying(255)
);

ALTER TABLE public.documenttypes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.documenttypes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.employeefiles (
    id bigint NOT NULL,
    filenickname character varying(255),
    localfilepath text,
    cloudfilepath text,
    createdby double precision,
    createdat timestamp without time zone,
    updatedby double precision,
    updatedat timestamp without time zone,
    documenttype double precision,
    ownerid double precision
);

ALTER TABLE public.employeefiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employeefiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.employees (
    id bigint NOT NULL,
    username character varying(255),
    lastlogints timestamp without time zone,
    employeefirstname character varying(255),
    employeelastname character varying(255),
    emailid character varying(255),
    deactivated boolean
);

ALTER TABLE public.employees ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employees_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.employeesinfo (
    id bigint NOT NULL,
    onboarddate timestamp without time zone,
    terminationdate timestamp without time zone,
    birthdaydate timestamp without time zone,
    employeedocumentpath text,
    empid double precision,
    phone_personal character varying(50),
    email_personal character varying(100),
    phone_emergency1 character varying(50),
    contact_emergency1 character varying(50),
    bankacctemp character varying(50),
    phone_emergency2 character varying(50),
    contact_emergency2 character varying(50),
    bankname character varying(100),
    showbirthday boolean DEFAULT false NOT NULL,
    avatarimage text,
    avatarusephoto boolean DEFAULT false NOT NULL
);

ALTER TABLE public.employeesinfo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employeesinfo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.employeeworkcalendar (
    id bigint NOT NULL,
    workyear double precision,
    labourhoursperyear double precision,
    holidaysamount double precision,
    corporateholidaysamount double precision,
    updatedat timestamp without time zone,
    updatedby double precision,
    empid double precision,
    importedholidays double precision
);

ALTER TABLE public.employeeworkcalendar ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."employeeworkcalendar_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.entity (
    id bigint NOT NULL,
    entitydesc character varying(255),
    legalname character varying(255),
    vatnumber character varying(64),
    address text,
    emailinvoicing character varying(255),
    webpage character varying(255),
    logo text,
    mailtransport character varying(8),
    mailsender character varying(255)
);

ALTER TABLE public.entity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.entity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.expenses (
    id bigint NOT NULL,
    picturetitle character varying(255),
    projectid double precision,
    employeeid double precision,
    amount double precision,
    categoryid double precision,
    expensets timestamp without time zone,
    ticketurl text,
    ticketfolderpath text,
    comments text,
    invoiceable boolean,
    countedat timestamp without time zone,
    countedby double precision,
    dumpid bigint
);

ALTER TABLE public.expenses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.expenses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.expensescategories (
    id bigint NOT NULL,
    categorydesc character varying(255)
);

ALTER TABLE public.expensescategories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.expensescategories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.global_settings (
    "Id" bigint NOT NULL,
    "GlobalSettingName" character varying(255),
    "GlobalSettingValue" character varying(255),
    "UpdatedBy" double precision,
    "UpdatedAt" timestamp without time zone
);

CREATE TABLE public.holidays (
    id bigint NOT NULL,
    holidaycode character varying(255),
    holidayyear double precision,
    holidaydate timestamp without time zone,
    holidaydesc character varying(255),
    holidayweekday character varying(255),
    source character varying(32)
);

ALTER TABLE public.holidays ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.holidays_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.invoicecurrencies (
    id bigint NOT NULL,
    code character varying(8) NOT NULL,
    symbol character varying(8) DEFAULT ''::character varying NOT NULL,
    label character varying(64) DEFAULT ''::character varying NOT NULL,
    sortorder integer DEFAULT 0 NOT NULL
);

ALTER TABLE public.invoicecurrencies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoicecurrencies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.invoicedocumentcontrols (
    id bigint NOT NULL,
    controlname character varying(255)
);

ALTER TABLE public.invoicedocumentcontrols ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoicedocumentcontrols_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.invoicedocumenttext (
    id bigint NOT NULL,
    controlnameid double precision,
    languageid double precision,
    languagetext text
);

ALTER TABLE public.invoicedocumenttext ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoicedocumenttext_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.invoicelineitems (
    id bigint NOT NULL,
    invoiceid bigint NOT NULL,
    sortorder integer DEFAULT 0 NOT NULL,
    description text,
    quantity numeric(14,2) DEFAULT 1 NOT NULL,
    unitprice numeric(14,2) DEFAULT 0 NOT NULL
);

ALTER TABLE public.invoicelineitems ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoicelineitems_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.invoicepaymentmethods (
    id bigint NOT NULL,
    methoddesc character varying(255)
);

ALTER TABLE public.invoicepaymentmethods ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoicepaymentmethods_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.invoices (
    id bigint NOT NULL,
    invoicecode character varying(255),
    invoicestatusid double precision,
    invoiceyear double precision,
    invoicemonth double precision,
    invoiceseq double precision,
    iscorrective boolean,
    sourceinvoiceid double precision,
    projectid double precision
);

ALTER TABLE public.invoices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.invoices_vattypes (
    id bigint NOT NULL,
    percentage double precision NOT NULL,
    disclaimer_es text,
    disclaimer_ca text,
    disclaimer_en text,
    vatdescription_short_es character varying(255),
    vatdescription_short_ca character varying(255),
    vatdescription_short_en character varying(255)
);

ALTER TABLE public.invoices_vattypes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoices_vattypes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.invoicescheduletypes (
    id bigint NOT NULL,
    scheduledesc character varying(255),
    defaultvalue double precision
);

ALTER TABLE public.invoicescheduletypes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoicescheduletypes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.invoicesdetails (
    id bigint NOT NULL,
    invoiceid double precision,
    amount double precision,
    invoicedate timestamp without time zone,
    invoicecomments text,
    invoiceduedate timestamp without time zone,
    invoicedipositdate timestamp without time zone,
    numocclient character varying(255),
    purchaseorder character varying(255),
    descriptionservice text,
    vatincluded boolean,
    vatamount double precision,
    invoicesentdate timestamp without time zone,
    dipositaccountid double precision,
    busspartnerid double precision,
    busspartnertoinvoiceid double precision,
    dumpid integer,
    vatid integer,
    updatedat timestamp with time zone,
    updatedby bigint,
    currency character varying(8) DEFAULT 'EUR'::character varying,
    emailedat timestamp with time zone,
    emailedby bigint,
    emailedto text,
    emailedcount integer DEFAULT 0 NOT NULL
);

ALTER TABLE public.invoicesdetails ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoicesdetails_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.invoicesstatus (
    id bigint NOT NULL,
    statusdesc character varying(255)
);

ALTER TABLE public.invoicesstatus ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoicesstatus_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.invoicingprojectrelease (
    id bigint NOT NULL,
    projectid double precision,
    proceedtoinvoice boolean,
    updatedat timestamp without time zone,
    updatedby double precision,
    invpaymethodid double precision,
    scheduletypeid double precision,
    numberofinvoices double precision,
    firstdate timestamp without time zone,
    lastdate timestamp without time zone
);

ALTER TABLE public.invoicingprojectrelease ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoicingprojectrelease_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.languages (
    id bigint NOT NULL,
    languagedesc character varying(255)
);

ALTER TABLE public.languages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.languages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.loglevels (
    id bigint NOT NULL,
    logleveldesc character varying(255)
);

ALTER TABLE public.loglevels ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.loglevels_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.modulerestrictions (
    id bigint NOT NULL,
    employeeid bigint NOT NULL,
    modulekey character varying(40) NOT NULL,
    restrictedat timestamp without time zone DEFAULT now(),
    restrictedby bigint
);

CREATE SEQUENCE public.modulerestrictions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.modulerestrictions_id_seq OWNED BY public.modulerestrictions.id;

CREATE TABLE public.projectchangelog (
    id bigint NOT NULL,
    projectid bigint NOT NULL,
    changedat timestamp with time zone DEFAULT now() NOT NULL,
    changedby bigint,
    summary text NOT NULL
);

CREATE SEQUENCE public.projectchangelog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.projectchangelog_id_seq OWNED BY public.projectchangelog.id;

CREATE TABLE public.projectdeliverables (
    id bigint NOT NULL,
    projectid double precision,
    deliverydate timestamp without time zone,
    deliverablename character varying(255),
    effectivedd timestamp without time zone,
    dumpid integer
);

ALTER TABLE public.projectdeliverables ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projectdeliverables_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.projectfiles (
    id bigint NOT NULL,
    filenickname character varying(255),
    localfilepath text,
    cloudfilepath text,
    createdby double precision,
    createdat timestamp without time zone,
    updatedby double precision,
    updatedat timestamp without time zone,
    documenttype double precision,
    ownerid double precision
);

ALTER TABLE public.projectfiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projectfiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.projectnotes (
    id bigint NOT NULL,
    projectid double precision,
    notes text,
    employeeid double precision,
    commentsts timestamp without time zone,
    lockforedit boolean,
    dumpid integer,
    usernoteid integer
);

ALTER TABLE public.projectnotes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projectnotes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.projectowners (
    id bigint NOT NULL,
    projectid double precision,
    projectownerid double precision,
    amount double precision
);

ALTER TABLE public.projectowners ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projectowners_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.projectportfolioprogress (
    id bigint NOT NULL,
    projectid double precision,
    progress double precision,
    updatedby double precision,
    updatedat timestamp without time zone,
    datadate timestamp without time zone
);

ALTER TABLE public.projectportfolioprogress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projectportfolioprogress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.projectquotations (
    id bigint NOT NULL,
    projectid double precision,
    amountquoted double precision,
    expenses double precision,
    details text,
    discountnegotiation double precision,
    finalquotation double precision,
    quotationdate timestamp without time zone,
    userid double precision,
    dumpid integer
);

ALTER TABLE public.projectquotations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projectquotations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.projectresources (
    id bigint NOT NULL,
    projectid double precision,
    amount double precision,
    resourceid double precision
);

CREATE TABLE public.projects (
    id bigint NOT NULL,
    projectnumber character varying(255),
    projectname character varying(255),
    entrydate timestamp without time zone,
    entityid double precision,
    biospectrumid double precision,
    projecttypeid double precision,
    busspartnerid double precision,
    projectstatusid double precision,
    projectyear double precision,
    busspartnertoinvoiceid double precision,
    lastupdated timestamp without time zone,
    lastupdatedby double precision,
    bprunningname character varying(255),
    notinvoiceable boolean
);

ALTER TABLE public.projects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.projectstatus (
    id bigint NOT NULL,
    projectstatusdesc character varying(255),
    ordinal double precision
);

ALTER TABLE public.projectstatus ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projectstatus_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.projectstatushistory (
    id bigint NOT NULL,
    projectid bigint NOT NULL,
    oldstatusid bigint,
    newstatusid bigint NOT NULL,
    changedat timestamp without time zone DEFAULT now(),
    changedby bigint
);

CREATE SEQUENCE public.projectstatushistory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.projectstatushistory_id_seq OWNED BY public.projectstatushistory.id;

CREATE TABLE public.projectstimetracking (
    id bigint NOT NULL,
    projectid double precision,
    projtimetrackweek double precision,
    projtimetrackdate timestamp without time zone,
    projtimetrackhours double precision,
    projtimetrackts timestamp without time zone,
    projexpenses double precision,
    islead boolean,
    lockforedit boolean,
    po_res character varying(255),
    userid double precision,
    dumpid integer
);

ALTER TABLE public.projectstimetracking ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projectstimetracking_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.projecttypes (
    id bigint NOT NULL,
    projecttypedesc character varying(255)
);

ALTER TABLE public.projecttypes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projecttypes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.projectresources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resourceallocation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.taxcompanies (
    id bigint NOT NULL,
    vatnumber character varying(255),
    emailinvoicing character varying(255),
    taxcompanyname character varying(255),
    businesspartnerid double precision,
    dumpid integer
);

ALTER TABLE public.taxcompanies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.taxcompanies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.taxcompaniesaddresses (
    id bigint NOT NULL,
    taxcompanyid double precision,
    streetname character varying(255),
    city character varying(255),
    state character varying(255),
    zipcode character varying(255),
    phonenumber character varying(255),
    phonenumber2 character varying(255),
    countryid double precision,
    sameaddress boolean,
    dumpid integer
);

ALTER TABLE public.taxcompaniesaddresses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.taxcompaniesaddresses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.timeallocationlog (
    id bigint NOT NULL,
    allocationdate timestamp without time zone,
    allocationhours double precision,
    allocationts timestamp without time zone,
    allocationweek double precision,
    holiday character varying(255),
    userid double precision,
    dumpid integer
);

ALTER TABLE public.timeallocationlog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.timeallocationlog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.timeoffapprovers (
    id bigint NOT NULL,
    employeeid bigint NOT NULL,
    grantedat timestamp without time zone DEFAULT now(),
    grantedby bigint
);

CREATE SEQUENCE public.timeoffapprovers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.timeoffapprovers_id_seq OWNED BY public.timeoffapprovers.id;

CREATE TABLE public.timeoffrequests (
    id bigint NOT NULL,
    empid double precision,
    startdate timestamp without time zone,
    enddate timestamp without time zone,
    daysrequested double precision,
    submittedat timestamp without time zone,
    approvedby double precision,
    approvedat timestamp without time zone,
    rejectedby double precision,
    rejectedat timestamp without time zone,
    rejectcomment character varying(255),
    withdrawnat timestamp without time zone,
    synced boolean,
    syncedat timestamp without time zone,
    calendar_event_id text
);

ALTER TABLE public.timeoffrequests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.timeoffrequests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.timeoffrequeststatus (
    id bigint NOT NULL,
    timeoffreqid double precision,
    statusid double precision
);

ALTER TABLE public.timeoffrequeststatus ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.timeoffrequeststatus_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.timeoffworkflowstatus (
    id bigint NOT NULL,
    workflowstatusdesc character varying(255)
);

ALTER TABLE public.timeoffworkflowstatus ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.timeoffworkflowstatus_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.admins ALTER COLUMN id SET DEFAULT nextval('public.admins_id_seq'::regclass);

ALTER TABLE ONLY public.businesspartnerchangelog ALTER COLUMN id SET DEFAULT nextval('public.businesspartnerchangelog_id_seq'::regclass);

ALTER TABLE ONLY public.modulerestrictions ALTER COLUMN id SET DEFAULT nextval('public.modulerestrictions_id_seq'::regclass);

ALTER TABLE ONLY public.projectchangelog ALTER COLUMN id SET DEFAULT nextval('public.projectchangelog_id_seq'::regclass);

ALTER TABLE ONLY public.projectstatushistory ALTER COLUMN id SET DEFAULT nextval('public.projectstatushistory_id_seq'::regclass);

ALTER TABLE ONLY public.timeoffapprovers ALTER COLUMN id SET DEFAULT nextval('public.timeoffapprovers_id_seq'::regclass);

ALTER TABLE ONLY public.actionsaudit
    ADD CONSTRAINT actionsaudit_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT addresses_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.admins
    ADD CONSTRAINT admins_employeeid_key UNIQUE (employeeid);

ALTER TABLE ONLY public.admins
    ADD CONSTRAINT admins_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.appconfig
    ADD CONSTRAINT appconfig_pkey PRIMARY KEY (configkey);

ALTER TABLE ONLY public.bankaccts
    ADD CONSTRAINT bankaccts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.biotechspectrums
    ADD CONSTRAINT biotechspectrums_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.businesspartnerchangelog
    ADD CONSTRAINT businesspartnerchangelog_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.businesspartners
    ADD CONSTRAINT businesspartners_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.businesspartnersnotes
    ADD CONSTRAINT businesspartnersnotes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.companytypes
    ADD CONSTRAINT companytypes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.contacts
    ADD CONSTRAINT contacts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.corporateworkcalendar
    ADD CONSTRAINT corporateworkcalendar_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.countries
    ADD CONSTRAINT countries_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.documenttypes
    ADD CONSTRAINT documenttypes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.employeefiles
    ADD CONSTRAINT employeefiles_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.employeesinfo
    ADD CONSTRAINT employeesinfo_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.employeeworkcalendar
    ADD CONSTRAINT employeeworkcalendar_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.entity
    ADD CONSTRAINT entity_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.expenses
    ADD CONSTRAINT expenses_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.expensescategories
    ADD CONSTRAINT expensescategories_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.global_settings
    ADD CONSTRAINT global_settings_pkey PRIMARY KEY ("Id");

ALTER TABLE ONLY public.holidays
    ADD CONSTRAINT holidays_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.invoicecurrencies
    ADD CONSTRAINT invoicecurrencies_code_key UNIQUE (code);

ALTER TABLE ONLY public.invoicecurrencies
    ADD CONSTRAINT invoicecurrencies_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.invoicedocumentcontrols
    ADD CONSTRAINT invoicedocumentcontrols_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.invoicedocumenttext
    ADD CONSTRAINT invoicedocumenttext_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.invoicelineitems
    ADD CONSTRAINT invoicelineitems_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.invoicepaymentmethods
    ADD CONSTRAINT invoicepaymentmethods_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT invoices_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.invoices_vattypes
    ADD CONSTRAINT invoices_vattypes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.invoicescheduletypes
    ADD CONSTRAINT invoicescheduletypes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.invoicesdetails
    ADD CONSTRAINT invoicesdetails_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.invoicesstatus
    ADD CONSTRAINT invoicesstatus_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.invoicingprojectrelease
    ADD CONSTRAINT invoicingprojectrelease_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.languages
    ADD CONSTRAINT languages_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.loglevels
    ADD CONSTRAINT loglevels_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.modulerestrictions
    ADD CONSTRAINT modulerestrictions_employeeid_modulekey_key UNIQUE (employeeid, modulekey);

ALTER TABLE ONLY public.modulerestrictions
    ADD CONSTRAINT modulerestrictions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.projectchangelog
    ADD CONSTRAINT projectchangelog_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.projectdeliverables
    ADD CONSTRAINT projectdeliverables_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.projectfiles
    ADD CONSTRAINT projectfiles_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.projectnotes
    ADD CONSTRAINT projectnotes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.projectowners
    ADD CONSTRAINT projectowners_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.projectportfolioprogress
    ADD CONSTRAINT projectportfolioprogress_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.projectquotations
    ADD CONSTRAINT projectquotations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.projectstatus
    ADD CONSTRAINT projectstatus_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.projectstatushistory
    ADD CONSTRAINT projectstatushistory_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.projectstimetracking
    ADD CONSTRAINT projectstimetracking_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.projecttypes
    ADD CONSTRAINT projecttypes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.projectresources
    ADD CONSTRAINT resourceallocation_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.taxcompanies
    ADD CONSTRAINT taxcompanies_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.taxcompaniesaddresses
    ADD CONSTRAINT taxcompaniesaddresses_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.timeallocationlog
    ADD CONSTRAINT timeallocationlog_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.timeoffapprovers
    ADD CONSTRAINT timeoffapprovers_employeeid_key UNIQUE (employeeid);

ALTER TABLE ONLY public.timeoffapprovers
    ADD CONSTRAINT timeoffapprovers_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.timeoffrequests
    ADD CONSTRAINT timeoffrequests_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.timeoffrequeststatus
    ADD CONSTRAINT timeoffrequeststatus_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.timeoffworkflowstatus
    ADD CONSTRAINT timeoffworkflowstatus_pkey PRIMARY KEY (id);

CREATE INDEX actionsaudit_actionts_idx ON public.actionsaudit USING btree (actionts DESC);

CREATE INDEX actionsaudit_actionuserid_idx ON public.actionsaudit USING btree (actionuserid);

CREATE INDEX idx_bpchangelog_bpid ON public.businesspartnerchangelog USING btree (businesspartnerid);

CREATE INDEX idx_projectchangelog_projectid ON public.projectchangelog USING btree (projectid);

CREATE INDEX idx_projectstatushistory_projectid ON public.projectstatushistory USING btree (projectid);

CREATE INDEX invoicelineitems_invoiceid_idx ON public.invoicelineitems USING btree (invoiceid);

ALTER TABLE ONLY public.businesspartnerchangelog
    ADD CONSTRAINT businesspartnerchangelog_businesspartnerid_fkey FOREIGN KEY (businesspartnerid) REFERENCES public.businesspartners(id);

ALTER TABLE ONLY public.businesspartnerchangelog
    ADD CONSTRAINT businesspartnerchangelog_changedby_fkey FOREIGN KEY (changedby) REFERENCES public.employees(id);

ALTER TABLE ONLY public.businesspartners
    ADD CONSTRAINT businesspartners_lastupdatedby_fkey FOREIGN KEY (lastupdatedby) REFERENCES public.employees(id);

ALTER TABLE ONLY public.projectchangelog
    ADD CONSTRAINT projectchangelog_changedby_fkey FOREIGN KEY (changedby) REFERENCES public.employees(id);

ALTER TABLE ONLY public.projectchangelog
    ADD CONSTRAINT projectchangelog_projectid_fkey FOREIGN KEY (projectid) REFERENCES public.projects(id);
