-- Up Migration
-- ==========================================================================
-- Customers & partners — Phase C4 (first slice): free tags.
-- --------------------------------------------------------------------------
-- See docs/customers-crm-roadmap.md (§3 Phase C4) and docs/customers-crm-
-- alignment.md §3.2 — Julia's "an organization may have several tags even
-- if it's displayed under one primary category" / "operational suppliers
-- should remain secondary tags". `businesspartners.category` (Phase C1)
-- stays the single primary category driving the landing-card view; tags
-- are the flexible, many-per-partner layer on top.
--
-- The rest of Phase C4 (saved segments, bulk actions, merge-duplicates,
-- CSV import) is deliberately NOT in this migration — each is a bigger,
-- separate exercise (merge-duplicates especially: it has to re-point
-- contacts, taxcompanies, notes, activities, opportunities and
-- projects.busspartnerid, and get that wrong once and it's a real support
-- problem). Tags are the contained, immediately useful piece.
-- ==========================================================================

CREATE TABLE public.crm_tags (
  id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label varchar(48) NOT NULL,
  color varchar(16),
  CONSTRAINT crm_tags_label_uq UNIQUE (label)
);

CREATE TABLE public.crm_partner_tags (
  businesspartnerid bigint NOT NULL REFERENCES public.businesspartners(id) ON DELETE CASCADE,
  tagid             bigint NOT NULL REFERENCES public.crm_tags(id) ON DELETE CASCADE,
  PRIMARY KEY (businesspartnerid, tagid)
);
CREATE INDEX crm_partner_tags_tagid_idx ON public.crm_partner_tags (tagid);

-- Down Migration

DROP TABLE IF EXISTS public.crm_partner_tags;
DROP TABLE IF EXISTS public.crm_tags;
