-- Up Migration
-- ==========================================================================
-- Customers & partners — Phase C4 (second slice): saved segments.
-- --------------------------------------------------------------------------
-- A named, reusable filter combination for the list page (stage/category/
-- role/tag/owner/search/includeArchived) — see docs/customers-crm-roadmap.md
-- §3 Phase C4. filter_json stores exactly the query-param object the
-- frontend already builds for GET /api/customers-partners, so applying a
-- saved segment is just "load these params" — no separate filter grammar.
-- ==========================================================================

CREATE TABLE public.crm_saved_segments (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name             varchar(64) NOT NULL,
  owner_employeeid bigint REFERENCES public.employees(id),
  shared           boolean NOT NULL DEFAULT false,
  filter_json      jsonb NOT NULL,
  created_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX crm_saved_segments_owner_idx ON public.crm_saved_segments (owner_employeeid);

-- Down Migration

DROP TABLE IF EXISTS public.crm_saved_segments;
