-- Up Migration
-- ==========================================================================
-- Veri*Factu (Spain, RD 1007/2023) — foundations.
-- --------------------------------------------------------------------------
-- Data model for bridging Ops invoicing to the AEAT via BOLD Software's API
-- as the SIF. No route wiring yet — see docs/verifactu-integration-roadmap.md
-- (phase V1) and server/lib/verifactu/.
--
-- The feature is gated by FEATURE_VERIFACTU (server/.env). These columns are
-- inert on every non-Spanish instance.
-- ==========================================================================

-- --- entity: per-entity Veri*Factu config ---------------------------------
-- One API-Key per issuing NIF is the conservative assumption (BOLD to
-- confirm), so the key lives on the entity, not in .env. It is a SERVER-ONLY
-- SECRET: routes must never return it — expose only a boolean "has key".
ALTER TABLE public.entity ADD COLUMN verifactu_enabled     boolean NOT NULL DEFAULT false;
ALTER TABLE public.entity ADD COLUMN verifactu_api_key     text;
ALTER TABLE public.entity ADD COLUMN verifactu_environment varchar(12) NOT NULL DEFAULT 'sandbox';  -- sandbox | production
ALTER TABLE public.entity ADD COLUMN invoice_series        varchar(16);  -- per-NIF series prefix, e.g. 'HITT'

-- --- taxcompanies: how the recipient is fiscally identified ---------------
--   NULL / 'nif'  -> Spanish NIF/NIE/CIF   -> BOLD `recipient.irsId`
--   '02'..'07'    -> foreign / non-NIF doc -> BOLD `recipient.id` + `idType`
--     02 VAT-intracommunity · 03 passport · 04 official document of the
--     recipient's country · 05 residence certificate · 06 other · 07 census NIF
ALTER TABLE public.taxcompanies ADD COLUMN fiscalidtype varchar(4);

-- --- invoices_vattypes -> Veri*Factu line classification ------------------
--   verifactu_vatoperation  S1 subject/not-exempt · S2 reverse charge ·
--                           N1/N2 not-subject · E1..E6 exempt
--   verifactu_vatkey        régimen de IVA (clave), 01 = general
--   verifactu_exemption_note free text shown on the PDF for exempt lines
ALTER TABLE public.invoices_vattypes ADD COLUMN verifactu_vatoperation  varchar(4);
ALTER TABLE public.invoices_vattypes ADD COLUMN verifactu_vatkey        varchar(4) NOT NULL DEFAULT '01';
ALTER TABLE public.invoices_vattypes ADD COLUMN verifactu_exemption_note text;

-- Seed defaults from the existing rate rows. A positive rate is an ordinary
-- taxed operation; a 0% row is treated as an Article 20 exemption (the note
-- already rendered on the PDF, lib/invoicePdf.js). Both are advisor-review
-- items before go-live (roadmap §4.4) — this is only a safe starting point.
UPDATE public.invoices_vattypes SET verifactu_vatoperation = 'S1'
 WHERE percentage IS NOT NULL AND percentage > 0 AND verifactu_vatoperation IS NULL;
UPDATE public.invoices_vattypes
   SET verifactu_vatoperation = 'E1',
       verifactu_exemption_note = 'Operación exenta de IVA (art. 20 Ley 37/1992)'
 WHERE percentage = 0 AND verifactu_vatoperation IS NULL;

-- --- invoicesdetails: draft vs issued, + per-invoice auto-submit ----------
-- A row with issued_at set is a legal invoice: its fiscal number is final,
-- it has been (or is queued to be) registered with the AEAT, and it is
-- immutable in the UI and API. draft = issued_at IS NULL.
ALTER TABLE public.invoicesdetails ADD COLUMN issued_at timestamptz;
ALTER TABLE public.invoicesdetails ADD COLUMN issued_by bigint;

-- "Send to AEAT automatically on issue" — the checkbox in the invoice modal,
-- checked by default. NULL is read as true so existing rows and the common
-- case need no value.
ALTER TABLE public.invoicesdetails ADD COLUMN verifactu_autosubmit boolean;

-- --- verifactu_records: one per registration / cancellation --------------
-- 1 'alta' row per issued invoice; a cancellation adds an 'anulacion' row.
-- Rows in aeat_state='pending' are retried by a background job (an AEAT/BOLD
-- outage must never block issuing — the AEAT developer FAQ requires issuing
-- to continue and the record to be re-sent when the service is back).
CREATE TABLE public.verifactu_records (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoiceid        bigint      NOT NULL,
  kind             varchar(12) NOT NULL DEFAULT 'alta',     -- alta | anulacion
  provider         varchar(24) NOT NULL DEFAULT 'bold',
  environment      varchar(12) NOT NULL DEFAULT 'sandbox',  -- sandbox | production
  queue_id         varchar(64),                             -- BOLD queueId — the handle for everything else
  request_id       varchar(64),
  aeat_state       varchar(12) NOT NULL DEFAULT 'pending',  -- pending | sent | error
  error_code       varchar(32),
  error_text       text,
  qr_png           text,                                    -- data:image/png;base64 — for the PDF
  verify_url       text,                                    -- AEAT verification URL (same value the QR encodes)
  chain_hash       varchar(128),                            -- hash of this record in the chain
  record_xml       text,                                    -- base64 RegistroAlta/Anulacion — kept as insurance
  submit_attempts  int         NOT NULL DEFAULT 0,
  submitted_at     timestamptz,
  state_checked_at timestamptz,
  submitted_by     bigint,
  created_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX verifactu_records_invoiceid_idx ON public.verifactu_records (invoiceid);
CREATE INDEX verifactu_records_pending_idx   ON public.verifactu_records (aeat_state) WHERE aeat_state = 'pending';

-- Down Migration

DROP TABLE IF EXISTS public.verifactu_records;

ALTER TABLE public.invoicesdetails  DROP COLUMN IF EXISTS verifactu_autosubmit;
ALTER TABLE public.invoicesdetails  DROP COLUMN IF EXISTS issued_by;
ALTER TABLE public.invoicesdetails  DROP COLUMN IF EXISTS issued_at;

ALTER TABLE public.invoices_vattypes DROP COLUMN IF EXISTS verifactu_exemption_note;
ALTER TABLE public.invoices_vattypes DROP COLUMN IF EXISTS verifactu_vatkey;
ALTER TABLE public.invoices_vattypes DROP COLUMN IF EXISTS verifactu_vatoperation;

ALTER TABLE public.taxcompanies DROP COLUMN IF EXISTS fiscalidtype;

ALTER TABLE public.entity DROP COLUMN IF EXISTS invoice_series;
ALTER TABLE public.entity DROP COLUMN IF EXISTS verifactu_environment;
ALTER TABLE public.entity DROP COLUMN IF EXISTS verifactu_api_key;
ALTER TABLE public.entity DROP COLUMN IF EXISTS verifactu_enabled;
