-- Up Migration
-- ==========================================================================
-- Time allocation → "Presence" — legal working-time register
-- (Spanish RDL 8/2019 → Art. 34.9 ET "registro de jornada"; Art. 35.5 ET
--  overtime totalisation).
--
-- LEGAL CONSTRAINTS BAKED INTO THIS SCHEMA
--   * Concrete start/end times per worker per day, breaks included
--     -> presence_events: an ordered stream of 'in'/'out' events; a break
--        is an 'out' then an 'in'.
--   * "Información no manipulable a posteriori, con trazabilidad"
--     -> APPEND-ONLY. A correction is a NEW row pointing at the one it
--        supersedes; the original is never mutated. A BEFORE UPDATE/DELETE
--        trigger enforces this at the database. Each row also carries a
--        per-employee SHA-256 hash chain (prev_hash -> row_hash) so silent
--        tampering is detectable (see server/lib/presence.js,
--        `npm run presence:verify`).
--   * 4-year retention, then deletion -> server/scripts/presence-purge.js
--     is the ONLY code allowed to delete, and only within a transaction
--     that sets `app.presence_purge = 'on'`.
--   * Access for worker / legal representatives / Inspección de Trabajo
--     -> presence_admins (+ config, act-on-behalf) and presence_viewers
--        (read + export ALL registers, no edit) allow-lists.
--   * GDPR: legal-obligation basis, purpose limitation, NO biometrics, NO
--     covert geolocation. location_label is self-declared context only;
--     entered_ip is audit metadata (admin-only), never surfaced as
--     "location".
--   * Times are Spain wall-clock, DST-aware -> everything is timestamptz +
--     explicit `AT TIME ZONE`; the org timezone lives in appconfig
--     ('presence.timezone', default 'Europe/Madrid').
-- ==========================================================================

-- --- the append-only event stream -------------------------------------
CREATE TABLE public.presence_events (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id    bigint      NOT NULL,          -- employees.id (no FK, matches savedreports)
    -- 'in'/'out' are clock boundaries; 'void' is a correction that removes
    -- the event it supersedes without adding a new boundary (the original
    -- is still preserved, just no longer effective).
    kind           varchar(4)  NOT NULL CHECK (kind IN ('in', 'out', 'void')),
    event_at       timestamptz NOT NULL,          -- the actual instant
    local_date     date        NOT NULL,          -- the "jornada" day (org-tz calendar date)
    source         varchar(8)  NOT NULL DEFAULT 'clock' CHECK (source IN ('clock', 'manual', 'import', 'system')),
    note           text,                          -- reason; required for manual entries / corrections
    location_label varchar(40),                   -- self-declared: office | remote | client | <free>
    supersedes_id  bigint REFERENCES public.presence_events(id),
    entered_by     bigint      NOT NULL,          -- who created THIS row (self, or an HR employee id)
    entered_at     timestamptz NOT NULL DEFAULT now(),
    entered_ip     varchar(64),
    prev_hash      char(64)    NOT NULL,          -- row_hash of this employee's previous event, or 64 zeros
    row_hash       char(64)    NOT NULL           -- sha256(prev_hash + canonical fields of this row)
);
CREATE INDEX presence_events_emp_date_idx   ON public.presence_events (employee_id, local_date);
CREATE INDEX presence_events_event_at_idx   ON public.presence_events (event_at);
CREATE INDEX presence_events_supersedes_idx ON public.presence_events (supersedes_id) WHERE supersedes_id IS NOT NULL;

COMMENT ON TABLE public.presence_events IS
  'Legal working-time register (RDL 8/2019 art. 34.9 ET). Append-only: no UPDATE, '
  'no DELETE except the retention purge. Corrections are new rows via supersedes_id. '
  'Purpose limited to the legal register + payroll totalisation — not for productivity monitoring.';

-- --- immutability guard ----------------------------------------------
CREATE FUNCTION public.presence_events_guard() RETURNS trigger
    LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' AND current_setting('app.presence_purge', true) = 'on' THEN
        RETURN OLD;  -- allowed only inside server/scripts/presence-purge.js
    END IF;
    RAISE EXCEPTION
        'presence_events is append-only (attempted %). Record a correction as a new row (supersedes_id); deletion is only via the retention purge.',
        TG_OP
        USING ERRCODE = 'restrict_violation';
END;
$$;

CREATE TRIGGER presence_events_immutable
    BEFORE UPDATE OR DELETE ON public.presence_events
    FOR EACH ROW EXECUTE FUNCTION public.presence_events_guard();

-- --- effective-dated contracted working time -------------------------
CREATE TABLE public.presence_contract (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id    bigint      NOT NULL,
    valid_from     date        NOT NULL,
    weekly_minutes int         NOT NULL,          -- contracted weekly working time
    workdays       varchar(15) NOT NULL DEFAULT '1,2,3,4,5',  -- ISO dow list (1=Mon .. 7=Sun)
    daily_minutes  int,                           -- optional explicit per-day; else weekly / count(workdays)
    note           text,
    created_by     bigint      NOT NULL,
    created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX presence_contract_emp_from_idx ON public.presence_contract (employee_id, valid_from DESC);

-- --- Art. 35.5 monthly totalisation ---------------------------------
CREATE TABLE public.presence_monthly (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id      bigint      NOT NULL,
    period_year      int         NOT NULL,
    period_month     int         NOT NULL CHECK (period_month BETWEEN 1 AND 12),
    worked_minutes   int         NOT NULL,
    expected_minutes int         NOT NULL,
    overtime_minutes int         NOT NULL DEFAULT 0,
    snapshot         jsonb       NOT NULL,        -- frozen per-day breakdown as delivered to the worker
    generated_at     timestamptz NOT NULL DEFAULT now(),
    generated_by     bigint,
    acknowledged_at  timestamptz,                -- worker confirmed receipt of the summary
    UNIQUE (employee_id, period_year, period_month)
);

-- --- access-tier allow-lists (mirror timeoffapprovers) --------------
CREATE TABLE public.presence_admins (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id bigint      NOT NULL UNIQUE,
    grantedat   timestamptz NOT NULL DEFAULT now(),
    grantedby   bigint,
    note        text
);
CREATE TABLE public.presence_viewers (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id bigint      NOT NULL UNIQUE,
    grantedat   timestamptz NOT NULL DEFAULT now(),
    grantedby   bigint,
    note        text                             -- e.g. "Comite de empresa", "Inspeccion - expediente NNN"
);

-- --- derived per-day summary (dashboards; exports recompute app-side) --
CREATE VIEW public.presence_day AS
WITH eff AS (
    SELECT e.employee_id, e.local_date, e.kind, e.event_at, e.source, e.id,
           LEAD(e.event_at) OVER w AS next_at,
           LEAD(e.kind)     OVER w AS next_kind
    FROM public.presence_events e
    WHERE e.kind IN ('in', 'out')
      AND NOT EXISTS (SELECT 1 FROM public.presence_events c WHERE c.supersedes_id = e.id)
    WINDOW w AS (PARTITION BY e.employee_id, e.local_date ORDER BY e.event_at, e.id)
)
SELECT
    employee_id,
    local_date,
    MIN(event_at) FILTER (WHERE kind = 'in')  AS first_in,
    MAX(event_at) FILTER (WHERE kind = 'out') AS last_out,
    COALESCE(SUM(EXTRACT(EPOCH FROM (next_at - event_at)) / 60.0)
             FILTER (WHERE kind = 'in' AND next_kind = 'out'), 0)::int AS worked_minutes,
    COUNT(*) FILTER (WHERE kind = 'in' AND next_kind = 'out')          AS segments,
    bool_or(source <> 'clock')                                         AS has_manual,
    bool_or(kind = 'in' AND next_at IS NULL)                           AS is_open
FROM eff
GROUP BY employee_id, local_date;

GRANT SELECT ON public.presence_day TO PUBLIC;

-- Down Migration
DROP VIEW IF EXISTS public.presence_day;
DROP TABLE IF EXISTS public.presence_viewers;
DROP TABLE IF EXISTS public.presence_admins;
DROP TABLE IF EXISTS public.presence_monthly;
DROP TABLE IF EXISTS public.presence_contract;
DROP TRIGGER IF EXISTS presence_events_immutable ON public.presence_events;
DROP FUNCTION IF EXISTS public.presence_events_guard();
DROP TABLE IF EXISTS public.presence_events;
