-- Up Migration
-- ==========================================================================
-- Customers & partners (Business partners → CRM) — Phase C1.
-- --------------------------------------------------------------------------
-- Account fields, relationship lifecycle, owner, and promoting people
-- (contacts) to first-class records so a person's org relationships have
-- their own history instead of one contact belonging to exactly one
-- business partner forever.
--
-- See docs/customers-crm-roadmap.md (§3 Phase C1) and
-- docs/customers-crm-alignment.md (§3.2-§3.4, §4.1, §4.4) for the design
-- discussion and the customer's (Julia's) confirmed vocabulary. No route or
-- UI wiring yet — that follows in a separate change.
-- ==========================================================================

-- --- businesspartners: relationship + ownership fields --------------------
-- roles: commercial classification, one partner can be several at once
-- (e.g. {customer, partner}) — deliberately not renaming the table/columns,
-- see the roadmap's "guiding constraints" (projects/invoicing joins on
-- businesspartnerid must not move).
ALTER TABLE public.businesspartners ADD COLUMN roles text[] NOT NULL DEFAULT '{}';

-- category: the single primary stakeholder category that drives the
-- landing-card view (e.g. "Sponsors & Industry", "Patient Organizations").
-- Free varchar for C1, not a lookup table — Phase C4 adds crm_tags for
-- flexible secondary tagging; category stays a simple, seedable-per-instance
-- value until there's a real need to normalise it.
ALTER TABLE public.businesspartners ADD COLUMN category varchar(32);

-- lifecycle_stage / temperature: relationship status, kept separate from
-- deal/project status on purpose (a partner can be an Active Partner with no
-- open project, or In Discussion with three). Vocabulary is Julia's
-- (alignment doc §3.3): new | in_discussion | active_partner | on_hold |
-- closed | former_partner. temperature (warm|hot) only means something
-- while in_discussion.
ALTER TABLE public.businesspartners ADD COLUMN lifecycle_stage varchar(16) NOT NULL DEFAULT 'new';
ALTER TABLE public.businesspartners ADD COLUMN temperature     varchar(4);

ALTER TABLE public.businesspartners ADD COLUMN owner_employeeid bigint REFERENCES public.employees(id);
ALTER TABLE public.businesspartners ADD COLUMN lead_source      varchar(32);

-- geo_scope: operating footprint, independent of the postal address on file
-- (local | regional | national | european | global). Region/city already
-- live on addresses.state / addresses.city — no new column for those.
ALTER TABLE public.businesspartners ADD COLUMN geo_scope varchar(16);

ALTER TABLE public.businesspartners ADD COLUMN archived_at timestamptz;

-- Backfill: a partner with any project not Closed/Cancelled is, in reality,
-- already an active relationship — mirrors the "alive" definition already
-- used by GET /api/business-partners (server/routes/businessPartners.js).
-- Every other existing row starts at the honest default: 'new' (we have no
-- signal to place it further along).
UPDATE public.businesspartners bp
SET lifecycle_stage = 'active_partner'
WHERE EXISTS (
  SELECT 1
  FROM public.projects p
  LEFT JOIN public.projectstatus ps ON ps.id = p.projectstatusid::bigint
  WHERE p.busspartnerid::bigint = bp.id
    AND (ps.projectstatusdesc IS NULL OR ps.projectstatusdesc NOT IN ('Closed', 'Cancelled'))
);

-- --- businesspartner_stage_history: preserve every lifecycle transition ---
-- Same "human-readable log per BP" pattern as businesspartnerchangelog, kept
-- separate because stage changes are structured (from/to + optional reason)
-- rather than free-text summaries.
CREATE TABLE public.businesspartner_stage_history (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  businesspartnerid bigint NOT NULL REFERENCES public.businesspartners(id),
  from_stage        varchar(16),
  to_stage          varchar(16) NOT NULL,
  changedat         timestamptz NOT NULL DEFAULT now(),
  changedby         bigint REFERENCES public.employees(id),
  reason            text
);
CREATE INDEX businesspartner_stage_history_bpid_idx
  ON public.businesspartner_stage_history (businesspartnerid, changedat DESC);

-- --- contacts: person-level enrichment (org-independent fields only) ------
-- Fields that describe the person regardless of which organization(s) they
-- are linked to. Org-specific fields (job title, decision role, influence,
-- reporting line) move to contact_org_roles below — a person's standing at
-- one company says nothing about their standing at another.
ALTER TABLE public.contacts ADD COLUMN linkedin_url    varchar(255);
ALTER TABLE public.contacts ADD COLUMN do_not_contact  boolean NOT NULL DEFAULT false;
ALTER TABLE public.contacts ADD COLUMN languageid      bigint REFERENCES public.languages(id);

-- --- contact_org_roles: promote contacts to first-class people ------------
-- Today contacts.businesspartnerid ties a contact to exactly one partner,
-- permanently. That breaks for a stakeholder-relationship model where the
-- same person can be a contact at several organizations over time, or (later
-- — Programme Operations, alignment doc §3.7) a participant with no employer
-- org at all. This table is the org-relationship; contacts.businesspartnerid
-- stays for now as the legacy "primary org" pointer existing routes read —
-- untouched here — until they're migrated onto this table in a follow-up
-- change (contacts.businesspartnerid is already nullable at the DB level, so
-- that migration needs no further schema change).
CREATE TABLE public.contact_org_roles (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contactid             bigint NOT NULL REFERENCES public.contacts(id) ON DELETE CASCADE,
  businesspartnerid     bigint NOT NULL REFERENCES public.businesspartners(id) ON DELETE CASCADE,
  "position"            varchar(255),
  is_primary            boolean NOT NULL DEFAULT false,
  -- decision_role: decision_maker | influencer | gatekeeper | user | unknown
  decision_role         varchar(24),
  -- influence: high | medium | low | unknown
  influence             varchar(16),
  -- stance: champion | supportive | neutral | skeptical | detractor | unknown
  stance                varchar(16),
  reports_to_contactid  bigint REFERENCES public.contacts(id),
  started_at            date,
  ended_at              date,
  created_at            timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX contact_org_roles_contactid_idx ON public.contact_org_roles (contactid);
CREATE INDEX contact_org_roles_bpid_idx      ON public.contact_org_roles (businesspartnerid);

-- Backfill one row per existing contact (position carried over as-is).
INSERT INTO public.contact_org_roles (contactid, businesspartnerid, "position", is_primary)
SELECT c.id, c.businesspartnerid::bigint, c."position", false
FROM public.contacts c
WHERE c.businesspartnerid IS NOT NULL;

-- Mark exactly one contact per partner as primary — the earliest-added one
-- (lowest id), since we have no other signal to prefer one over another.
UPDATE public.contact_org_roles cor
SET is_primary = true
FROM (
  SELECT DISTINCT ON (businesspartnerid) id
  FROM public.contact_org_roles
  ORDER BY businesspartnerid, id
) first_role
WHERE cor.id = first_role.id;

-- Enforce it going forward: at most one *active* primary contact per partner.
CREATE UNIQUE INDEX contact_org_roles_one_primary_uq
  ON public.contact_org_roles (businesspartnerid)
  WHERE is_primary AND ended_at IS NULL;

-- Down Migration

DROP INDEX IF EXISTS public.contact_org_roles_one_primary_uq;
DROP TABLE IF EXISTS public.contact_org_roles;

ALTER TABLE public.contacts DROP COLUMN IF EXISTS languageid;
ALTER TABLE public.contacts DROP COLUMN IF EXISTS do_not_contact;
ALTER TABLE public.contacts DROP COLUMN IF EXISTS linkedin_url;

DROP TABLE IF EXISTS public.businesspartner_stage_history;

ALTER TABLE public.businesspartners DROP COLUMN IF EXISTS archived_at;
ALTER TABLE public.businesspartners DROP COLUMN IF EXISTS geo_scope;
ALTER TABLE public.businesspartners DROP COLUMN IF EXISTS lead_source;
ALTER TABLE public.businesspartners DROP COLUMN IF EXISTS owner_employeeid;
ALTER TABLE public.businesspartners DROP COLUMN IF EXISTS temperature;
ALTER TABLE public.businesspartners DROP COLUMN IF EXISTS lifecycle_stage;
ALTER TABLE public.businesspartners DROP COLUMN IF EXISTS category;
ALTER TABLE public.businesspartners DROP COLUMN IF EXISTS roles;
