-- Up Migration
-- ==========================================================================
-- external_sync — bookkeeping for the Settings → Sync backup engine.
-- --------------------------------------------------------------------------
-- One row per (kind, ref_id): the last time that app object was pushed to
-- the company's external storage (OneDrive / SharePoint via lib/graph.js).
--
--   kind       'expense_doc' | 'invoice_doc' | 'project_folder'
--   ref_id     expenses.id  | invoices.id   | projects.id
--   source_sig a cheap fingerprint of the source (e.g. expenses.ticketurl,
--              an invoice detail hash) — lets the catch-up job tell "already
--              synced, unchanged" from "changed since, re-push".
--   status     'ok' | 'error'  (errors are retried by the next job run)
--
-- Best-effort: a failure here never blocks the upload / create that
-- triggered it. See server/lib/externalSync.js and docs/external-sync.md.

CREATE TABLE public.external_sync (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind       varchar(16) NOT NULL,
  ref_id     bigint      NOT NULL,
  source_sig text,
  target     text,
  remote_id  text,
  remote_url text,
  remote_path text,
  status     varchar(8)  NOT NULL DEFAULT 'ok',
  error      text,
  attempts   int         NOT NULL DEFAULT 1,
  synced_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (kind, ref_id)
);
CREATE INDEX external_sync_status_idx ON public.external_sync (status) WHERE status <> 'ok';

-- Down Migration
DROP TABLE IF EXISTS public.external_sync;
