-- Up Migration
-- ==========================================================================
-- Customers & partners — Phase C2: communication timeline (crm_activities)
-- and a platform-wide Task Manager (tasks).
-- --------------------------------------------------------------------------
-- See docs/customers-crm-roadmap.md (§3 Phase C2) and docs/customers-crm-
-- alignment.md (§3.1, §3.4, §4.4 Q3 — Julia confirmed this is platform-wide,
-- not CRM-only, and belongs in Phase 1). No route/UI wiring yet.
--
-- crm_activities.opportunityid is a bare column with no FK: Phase C3
-- (crm_opportunities, not built yet) will point at it. Same reasoning as
-- every other loosely-typed legacy id column in this schema — add the
-- constraint once the referenced table exists, don't block on ordering.
--
-- tasks is intentionally NOT nested under crm_* — it's meant to carry
-- tasks for projects and (later) Programme Operations cohorts too, not
-- just customers/partners. entity_type/entity_id is a polymorphic link
-- (no FK possible — the target table depends on entity_type), same
-- pattern needed for the later Relationship Map role-placeholders table.
-- ==========================================================================

-- --- crm_activities: one row per logged interaction -----------------------
CREATE TABLE public.crm_activities (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  businesspartnerid bigint REFERENCES public.businesspartners(id),
  contactid         bigint REFERENCES public.contacts(id),
  opportunityid     bigint,                     -- FK added once crm_opportunities exists (Phase C3)
  kind              varchar(16) NOT NULL,        -- call | meeting | email | note | site_visit | other
  occurred_at       timestamptz NOT NULL DEFAULT now(),
  summary           text NOT NULL,
  outcome           varchar(16),                 -- positive | neutral | negative | null
  agreed_next_step  text,
  logged_by         bigint REFERENCES public.employees(id),
  created_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX crm_activities_bpid_idx        ON public.crm_activities (businesspartnerid, occurred_at DESC);
CREATE INDEX crm_activities_contactid_idx   ON public.crm_activities (contactid);
CREATE INDEX crm_activities_opportunity_idx ON public.crm_activities (opportunityid);

-- Who took part — a contact, an employee, or (for an internal-only note)
-- neither field required beyond at least one of the two.
CREATE TABLE public.crm_activity_participants (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activityid bigint NOT NULL REFERENCES public.crm_activities(id) ON DELETE CASCADE,
  contactid  bigint REFERENCES public.contacts(id),
  employeeid bigint REFERENCES public.employees(id),
  CONSTRAINT crm_activity_participants_who_chk CHECK (contactid IS NOT NULL OR employeeid IS NOT NULL)
);
CREATE INDEX crm_activity_participants_activityid_idx ON public.crm_activity_participants (activityid);

-- --- tasks: platform-wide, not CRM-only ------------------------------------
CREATE TABLE public.tasks (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title             varchar(255) NOT NULL,
  description       text,
  status            varchar(12) NOT NULL DEFAULT 'open',  -- open | done | cancelled
  priority          varchar(8),                            -- low | medium | high | null
  owner_employeeid  bigint REFERENCES public.employees(id),
  due_date          date,
  reminder_at       timestamptz,
  entity_type       varchar(24),                           -- 'customer_partner' | 'contact' | 'project' | null
  entity_id         bigint,
  source_activityid bigint REFERENCES public.crm_activities(id),
  completed_at      timestamptz,
  created_by        bigint REFERENCES public.employees(id),
  created_at        timestamptz NOT NULL DEFAULT now()
);
-- "My open tasks, soonest due date first" — the home-dashboard + Task
-- Manager "My tasks" view's exact query shape.
CREATE INDEX tasks_owner_open_idx ON public.tasks (owner_employeeid, due_date) WHERE status = 'open';
CREATE INDEX tasks_entity_idx     ON public.tasks (entity_type, entity_id);

CREATE TABLE public.task_collaborators (
  taskid     bigint NOT NULL REFERENCES public.tasks(id) ON DELETE CASCADE,
  employeeid bigint NOT NULL REFERENCES public.employees(id),
  PRIMARY KEY (taskid, employeeid)
);

-- Down Migration

DROP TABLE IF EXISTS public.task_collaborators;
DROP TABLE IF EXISTS public.tasks;
DROP TABLE IF EXISTS public.crm_activity_participants;
DROP TABLE IF EXISTS public.crm_activities;
