-- Up Migration
-- ==========================================================================
-- email_transports — DB-managed outbound email transports, replacing the
-- GRAPH_MAIL_* / SMTP_* env vars (see docs/email-transports.md).
-- --------------------------------------------------------------------------
-- One row per named transport. Each is either a Microsoft Graph app
-- (client-credentials, Mail.Send) or an SMTP account. The two secret
-- columns hold AES-256-GCM ciphertext produced by server/lib/secrets.js
-- ("gcm.v1.<base64>"); the key is APP_ENCRYPTION_KEY in the instance env.
--
-- A billing entity points at a transport via entity.mail_transport_id
-- (chosen in Settings -> Entities). When an entity has none, the app-level
-- default in appconfig 'email.default_transport_id' is used; if that is
-- unset too, invoice email for that entity fails with a clear 503.
-- ==========================================================================

CREATE TABLE public.email_transports (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          varchar(80)  NOT NULL,
  kind          varchar(8)   NOT NULL CHECK (kind IN ('graph', 'smtp')),
  from_address  varchar(255) NOT NULL,
  active        boolean      NOT NULL DEFAULT true,
  -- Microsoft Graph (kind = 'graph')
  graph_tenant_id     varchar(64),
  graph_client_id     varchar(64),
  graph_client_secret text,              -- gcm.v1.<base64> ciphertext
  -- SMTP (kind = 'smtp')
  smtp_host     varchar(255),
  smtp_port     integer,
  smtp_user     varchar(255),
  smtp_pass     text,                    -- gcm.v1.<base64> ciphertext
  smtp_secure   boolean      NOT NULL DEFAULT false,
  created_at    timestamptz  NOT NULL DEFAULT now(),
  updated_at    timestamptz  NOT NULL DEFAULT now(),
  updated_by    bigint
);

CREATE UNIQUE INDEX email_transports_name_key ON public.email_transports (lower(name));

-- The transport a billing entity sends its invoices through. NULL -> use the
-- appconfig 'email.default_transport_id'. ON DELETE SET NULL so removing a
-- transport just drops the link (the DELETE route blocks it anyway while any
-- entity still points here).
ALTER TABLE public.entity
  ADD COLUMN mail_transport_id bigint REFERENCES public.email_transports(id) ON DELETE SET NULL;

-- Down Migration
ALTER TABLE public.entity DROP COLUMN IF EXISTS mail_transport_id;
DROP TABLE IF EXISTS public.email_transports;
DELETE FROM public.appconfig WHERE configkey = 'email.default_transport_id';
