-- Up Migration
-- ==========================================================================
-- Customers & partners — Phase C3: the pre-project opportunities funnel.
-- --------------------------------------------------------------------------
-- See docs/customers-crm-alignment.md §3.5 (revised) and §4.4 Q2 — Julia
-- confirmed she needs to track potential deals before they're a project at
-- all (a name, a scope, a number). This is deliberately a short, linear
-- funnel (identified -> qualifying -> proposal_pending -> converted/lost),
-- not a configurable pipeline-stage system: once a deal is real enough to
-- convert, the existing Projects board (Lead/Oferta/Guanyat) takes over as
-- the record of truth — an opportunity and its converted project are never
-- both "open" at once.
-- ==========================================================================

CREATE TABLE public.crm_opportunities (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  businesspartnerid bigint NOT NULL REFERENCES public.businesspartners(id),
  name              varchar(255) NOT NULL,
  -- identified | qualifying | proposal_pending | converted | lost
  stage             varchar(20) NOT NULL DEFAULT 'identified',
  estimated_value   numeric(14,2),
  currencyid        bigint REFERENCES public.invoicecurrencies(id),
  owner_employeeid  bigint REFERENCES public.employees(id),
  expected_close    date,
  source            varchar(32),
  lost_reason       varchar(128),
  -- Set once "Convert to project" runs (see routes/businessPartners.js
  -- POST /:id/opportunities/:oppId/convert). A converted opportunity is
  -- read-only from then on — the project is the record of truth.
  projectid         bigint REFERENCES public.projects(id),
  created_by        bigint REFERENCES public.employees(id),
  created_at        timestamptz NOT NULL DEFAULT now(),
  closed_at         timestamptz
);
CREATE INDEX crm_opportunities_bpid_idx  ON public.crm_opportunities (businesspartnerid);
CREATE INDEX crm_opportunities_stage_idx ON public.crm_opportunities (stage);

CREATE TABLE public.crm_opportunity_stage_history (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  opportunityid bigint NOT NULL REFERENCES public.crm_opportunities(id) ON DELETE CASCADE,
  from_stage    varchar(20),
  to_stage      varchar(20) NOT NULL,
  changedat     timestamptz NOT NULL DEFAULT now(),
  changedby     bigint REFERENCES public.employees(id),
  reason        text
);
CREATE INDEX crm_opportunity_stage_history_oppid_idx
  ON public.crm_opportunity_stage_history (opportunityid, changedat DESC);

-- projects: pre-sale value fields. Populated on "Convert to project" (from
-- the opportunity's own estimated_value/currency), or settable directly on
-- an existing Lead/Oferta project. Nullable — most historic projects will
-- never have these.
ALTER TABLE public.projects ADD COLUMN estimated_value numeric(14,2);
ALTER TABLE public.projects ADD COLUMN currencyid      bigint REFERENCES public.invoicecurrencies(id);

-- Down Migration

ALTER TABLE public.projects DROP COLUMN IF EXISTS currencyid;
ALTER TABLE public.projects DROP COLUMN IF EXISTS estimated_value;

DROP TABLE IF EXISTS public.crm_opportunity_stage_history;
DROP TABLE IF EXISTS public.crm_opportunities;
