/**
 * Audit log
 * ---------------------------------------------------------------------------
 * A single append-only table recording security- and data-relevant actions:
 * sign in / sign out (with client IP + reported device), project creation,
 * project time-tracking inserts/updates/deletes, and business-partner
 * inserts/updates. Read by admins only via GET /api/audit/logs
 * (routes/audit.js) and the Settings → Auditing tab.
 *
 * The table is created idempotently at runtime (CREATE TABLE IF NOT EXISTS)
 * — mirrored in server/db/schema-changes.sql — so a deploy needs no manual
 * migration step. logAudit() is best-effort: it never throws back to the
 * caller, so an audit-write failure can't break the action being audited.
 *
 * "Computer name" note: a browser cannot read the client's OS hostname, so
 * `computername` holds the best a web page can report — the platform string
 * from navigator.userAgentData / navigator.platform. The full user-agent is
 * kept alongside it.
 * ---------------------------------------------------------------------------
 */
const { pool } = require("../config/db");

let ready = null;
function ensureAuditSchema() {
  if (!ready) {
    ready = pool
      .query(`
        CREATE TABLE IF NOT EXISTS public.auditlog (
          id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          at          timestamp without time zone NOT NULL DEFAULT now(),
          employeeid  bigint,
          username    varchar(255),
          action      varchar(64) NOT NULL,
          entitytype  varchar(32),
          entityid    bigint,
          summary     text,
          ipaddress   varchar(64),
          computername varchar(255),
          useragent   text
        )
      `)
      .then(() =>
        pool.query(`CREATE INDEX IF NOT EXISTS auditlog_at_idx ON public.auditlog (at DESC)`)
      )
      .then(() =>
        pool.query(`CREATE INDEX IF NOT EXISTS auditlog_employeeid_idx ON public.auditlog (employeeid)`)
      )
      .catch((err) => {
        ready = null; // let a later call retry
        throw err;
      });
  }
  return ready;
}

function clientIp(req) {
  const fwd = req.headers["x-forwarded-for"];
  if (fwd) return String(fwd).split(",")[0].trim() || null;
  return req.socket?.remoteAddress || req.ip || null;
}

/**
 * Best-effort audit write. Never throws — logs and swallows on failure.
 * @param {import('express').Request} req  for IP + the resolved req.hittUser
 * @param {object} entry { action, entityType?, entityId?, summary?, computerName?, userAgent? }
 */
async function logAudit(req, entry) {
  try {
    await ensureAuditSchema();
    const u = (req && req.hittUser) || {};
    const {
      action,
      entityType = null,
      entityId = null,
      summary = null,
      computerName = null,
      userAgent = null,
    } = entry || {};
    await pool.query(
      `INSERT INTO auditlog
         (employeeid, username, action, entitytype, entityid, summary, ipaddress, computername, useragent)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)`,
      [
        u.employeeId || null,
        u.raw || null,
        action,
        entityType,
        entityId != null && entityId !== "" ? String(entityId) : null,
        summary,
        req ? clientIp(req) : null,
        computerName ? String(computerName).slice(0, 255) : null,
        userAgent ? String(userAgent).slice(0, 2000) : null,
      ]
    );
  } catch (err) {
    console.error("[audit] failed to write audit entry:", err.message);
  }
}

module.exports = { logAudit, ensureAuditSchema };
