-- ==========================================================================
-- HITT Ops — incremental schema changes
-- --------------------------------------------------------------------------
-- This project has no migration framework. Changes to the existing
-- PostgreSQL schema are collected here and are also applied idempotently at
-- runtime by the code that needs them, so a deploy doesn't require running
-- this by hand. It's kept for anyone who prefers to apply changes
-- explicitly / review them in one place.
-- ==========================================================================

-- 2026-08 — Settings "Holidays" tab
-- --------------------------------------------------------------------------
-- Tag every holidays row with where it came from, so re-importing the
-- public-holiday feed (source = 'catalonia') never clobbers HR's own
-- HITT holidays (source = 'hitt') or pre-existing rows (source = 'legacy').
-- Applied at runtime by ensureSettingsSchema() in server/routes/settings.js.
ALTER TABLE public.holidays ADD COLUMN IF NOT EXISTS source varchar(32);
UPDATE public.holidays SET source = 'legacy' WHERE source IS NULL;

-- 2026-08 — Settings "Work calendar" tab
-- --------------------------------------------------------------------------
-- No column changes. corporateworkcalendar already has workyear,
-- holidaysamount (leave-day allowance), labourhoursperyear (working hours),
-- corporateholidaysamount, updatedat, updatedby. The Settings tab upserts
-- one row per year; the time-off balance view (server/routes/timeOff.js)
-- falls back to it when an employee has no employeeworkcalendar row.
-- (Optional) enforce one row per year if you want a hard guarantee:
-- CREATE UNIQUE INDEX IF NOT EXISTS corporateworkcalendar_workyear_uidx
--   ON public.corporateworkcalendar (workyear);

-- 2026-08 — Settings "Paths" tab + employee detail
-- --------------------------------------------------------------------------
-- appconfig is a small key/value store for configurable paths (currently
-- just onedrive.employee_docs_base). Created at runtime by
-- ensureSettingsSchema() in server/routes/settings.js.
CREATE TABLE IF NOT EXISTS public.appconfig (
    configkey   varchar(64) PRIMARY KEY,
    configvalue text,
    updatedat   timestamp without time zone,
    updatedby   bigint
);
-- The add/edit-user modal also reads/writes public.employeesinfo (a
-- pre-existing table, one row per employee via empid). No changes needed;
-- employeedocumentpath is set to <appconfig base>/<username> on save.

-- 2026-08 — BP edit form: tax companies + addresses
-- --------------------------------------------------------------------------
-- No schema changes. taxcompanies / taxcompaniesaddresses / addresses are
-- all pre-existing. The BP modal's Invoicing tab now does full CRUD on a
-- BP's tax companies; each tax-company address either mirrors the BP
-- address (taxcompaniesaddresses.sameaddress = true, kept in sync when the
-- BP address is edited) or holds its own. Deleting a tax company is blocked
-- while it's assigned to a project or referenced by an invoice.

-- 2026-08 — Expenses module
-- --------------------------------------------------------------------------
-- Company expense records — meals, hotels, flights, car rentals, materials,
-- plus internal expenses (no project). One optional evidence file per row,
-- stored on the API host under UPLOAD_DIR (default server/uploads/expenses,
-- gitignored) — documentpath holds the stored filename. Created at runtime
-- by ensureSchema() in server/routes/expenses.js.
CREATE TABLE IF NOT EXISTS public.companyexpenses (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expensedate  date,
    category     varchar(64),
    description  text,
    amount       numeric(12,2),
    currency     varchar(8) DEFAULT 'EUR',
    projectid    bigint,                -- NULL = internal expense
    isinternal   boolean DEFAULT false,
    paidby       bigint,
    documentpath text,
    documentname varchar(255),
    documentmime varchar(100),
    createdat    timestamp without time zone DEFAULT now(),
    createdby    bigint,
    updatedat    timestamp without time zone,
    updatedby    bigint
);
CREATE INDEX IF NOT EXISTS companyexpenses_projectid_idx ON public.companyexpenses (projectid);
CREATE INDEX IF NOT EXISTS companyexpenses_date_idx ON public.companyexpenses (expensedate DESC);
-- Backend dependency: `npm install` now also pulls in `multer` (file
-- uploads). New optional env var: UPLOAD_DIR.

-- 2026-08 — Auditing (Settings → Auditing, admins only)
-- --------------------------------------------------------------------------
-- Every security-/data-relevant action is appended to public.actionsaudit
-- (the same table the Access app used). Its base columns already exist
-- (actionuserid, actiondesc, actionts, actioncomputer, actionenvironment,
-- loglevel). These extras are added at runtime by ensureAuditSchema() in
-- server/lib/audit.js:
ALTER TABLE public.actionsaudit ADD COLUMN IF NOT EXISTS actionusername varchar(255);
ALTER TABLE public.actionsaudit ADD COLUMN IF NOT EXISTS actionkind varchar(64);
ALTER TABLE public.actionsaudit ADD COLUMN IF NOT EXISTS actionip varchar(64);
CREATE INDEX IF NOT EXISTS actionsaudit_actionts_idx ON public.actionsaudit (actionts DESC);
CREATE INDEX IF NOT EXISTS actionsaudit_actionuserid_idx ON public.actionsaudit (actionuserid);

-- An earlier build briefly created a separate public.auditlog table; it is
-- unused now. Drop it if it exists in your database:
DROP TABLE IF EXISTS public.auditlog;
